### ISSUE TITLE
Enforce rule message formatting/quality

### ISSUE THREAD

**Issue by sabrinabrogren** [returntocorp/sgrep-rules#1006]
For the sake of inline PR comments and the registry, we should enforce some sort of standards around rule messaging. Some examples:
![image](https://user-images.githubusercontent.com/15618941/99428893-3f4ba800-28d5-11eb-9821-173a5fd74c79.png)
Newlines in the middle of the message mess up formatting. (See more inline pr comment examples [here](https://github.com/returntocorp/semgrep/pull/2042))
![image](https://user-images.githubusercontent.com/15618941/99428941-4ecaf100-28d5-11eb-8f29-a3250ab769c0.png)
At first glance, this looks like an incomplete message.

Additionally, some feedback from inline PR comment dry runs is that users would appreciate not only a brief explanation of what's wrong, but how to fix it (in the case where just giving an autofix isn't possible). A lot of messages have this information, but others don't.

**Comment by minusworld** [comment]
Related to message content are these new CONTRIBUTING guidelines on semgrep-rules:
https://github.com/returntocorp/semgrep-rules/blob/develop/CONTRIBUTING.md#rule-messages

**Comment by minusworld** [comment]
Also, one way we can fix this is by stripping newlines from all messages using a YAML-ism: 
`>-` will strip all newlines

**Comment by sabrinabrogren** [comment]
Thanks @minusworld for pointing out those guidelines! I wonder if there's a way to automate enforcing some of those...

I think stripping newlines would _mostly_ work, but there are some cases where we do want the newlines, like in this case with a code block:
![image](https://user-images.githubusercontent.com/15618941/99443868-657b4300-28e9-11eb-9490-7438399d1899.png)
(Ignore that it messed up the rest of the comment formatting 😅 )
