### ISSUE TITLE
don't use FloatField to store money (use DecimalField instead)

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#105]
check for common money value field names?

**Comment by minusworld** [comment]
https://stackoverflow.com/questions/2569015/django-floatfield-or-decimalfield-for-currency/2569044#2569044

**Comment by minusworld** [comment]
Prototype in this branch: https://github.com/returntocorp/sgrep-rules/tree/use-decimalfield-for-money

**Comment by minusworld** [comment]
blocked on release of sgrep 0.4.7 analzyzer

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/filter/632

**Comment by minusworld** [comment]
Hunting for FloatField/DecimalField names: https://dev.massive.ret2.co/triager/filter/575

**Comment by minusworld** [comment]
merged
