### ISSUE TITLE
Detecting absence of Java annotations

### ISSUE THREAD

**Issue by nightwatchcyber** [returntocorp/sgrep-rules#1056]
**Describe the bug**
Trying to figure out how to detect the absence of a Java annotation when other annotations are used.

Here is one that detect the presence of "@RolesAllowed" within another one:
https://semgrep.dev/s/nightwatchcyber:java_annotations_inverse
```
  patterns:
    - pattern: |
          @RolesAllowed(...)
    - pattern-inside: |
        @RequestMapping(...)
        $X $METHOD(...) { ... }
```

However, changing this to "pattern-not" doesn't work, instead it detects everything:
https://semgrep.dev/s/nightwatchcyber:java_annotations_inverse_2
```
  patterns:
    - pattern-not: |
          @RolesAllowed(...)
    - pattern-inside: |
        @RequestMapping(...)
        $X $METHOD(...) { ... }
```

Trying ellipses doesn't help, instead there is an error:
```
  patterns:
    - pattern-not: |
          @RolesAllowed(...)
          ...
    - pattern-inside: |
        @RequestMapping(...)
        $X $METHOD(...) { ... }
```
Or:
```
  patterns:
    - pattern-not: |
          @RolesAllowed(...)
    - pattern-inside: |
        @RequestMapping(...)
        ...
        $X $METHOD(...) { ... }
```

**Comment by dlukeomalley** [comment]
~@nightwatchcyber Thanks for opening! What was the fix or workaround you found?~

Disregard, I see https://github.com/returntocorp/semgrep/issues/2320 now 👍
