### ISSUE TITLE
don't use ForeignKey(unique=True) - OneToOneField instead

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#106]

**Comment by ulziibay** [comment]
OneToOneField vs ForeignKey(unique=True)  are not exactly equivalent. See https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.OneToOneField
> A one-to-one relationship. Conceptually, this is similar to a ForeignKey with unique=True, but the “reverse” side of the relation will directly return a single object.
Hence, upselling OneToOneField is wrong in my opinion!

**Comment by minusworld** [comment]
Yeah, I was wondering about that myself.  This seems preferential/stylistic... but I just wrote the check in about 3 minutes anyway 😅
