### ISSUE TITLE
if unique=True and blank=True, null=True must be set

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#107]

**Comment by nbrahms** [comment]
cf. https://docs.djangoproject.com/en/3.0/ref/models/fields/

**Comment by minusworld** [comment]
References:
- https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.Field.null

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/jobs/569?page=1&sort_on=repo_url&sort_by=asc

**Comment by minusworld** [comment]
https://github.com/returntocorp/sgrep-rules/pull/179

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/filter/581
