### ISSUE TITLE
use null=True if blank=True on non-text-fields

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#108]

**Comment by minusworld** [comment]
https://stackoverflow.com/questions/8609192/differentiate-null-true-blank-true-in-django

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/jobs/570?page=1&sort_on=repo_url&sort_by=asc

**Comment by minusworld** [comment]
https://github.com/returntocorp/sgrep-rules/pull/179

**Comment by minusworld** [comment]
Check improvements:
Exclude:
- FilePathField
- URLField
- ImageField
- ForeignKey?
- ManyToManyField?
- DateField?
