### ISSUE TITLE
[Rule] Check that fullstory censors sensitive fields

### ISSUE THREAD

**Issue by colleend** [returntocorp/sgrep-rules#1095]
**Rule Description**
Fullstory should censor specific sensitive fields with [.fs-exclude class](https://help.fullstory.com/hc/en-us/articles/360020623574-How-do-I-protect-my-users-privacy-in-FullStory-#code-first).

*What does this rule intend to find?*
Instances where Fullstory does not censor sensitive fields.

**Additional information**
https://help.fullstory.com/hc/en-us/articles/360020623574-How-do-I-protect-my-users-privacy-in-FullStory-#code-first

**PR Checklist**
- [ ] This ticket has links, references, or examples.
- [ ] The rule has **true positive** and **true negative** test cases in a file that matches the rule name.

> If the rule is `my-rule`, the test file name should be `my-rule.js`.
>
> True positives are marked by comments with `ruleid: <my-rule>` and true negatives are marked by comments with `ok: <my-rule>`.

- [ ] The rule has a good message. A good message includes:

> 1. A description of the pattern (e.g., missing parameter, dangerous flag, out-of-order function calls).
> 1. A description of why this pattern was detected (e.g., logic bug, introduces a security vulnerability, bad practice).
> 1. An alternative that resolves the issue (e.g., use another function, validate data first, discard the dangerous flag).

- [ ] After the PR has been reviewed and approved, merge the rule and close this ticket! Thanks for contributing!

**Comment by underyx** [comment]
do we have any idea how to recognize what fields are sensitive? 🤔 it also sounds like a long shot to add this to any public ruleset btw, since few projects will actually use FullStory

**Comment by colleend** [comment]
That's a very good point -- it'll be difficult to recognize sensitive fields, although it's definitely possible to detect cases where we don't use .fs-exclude.

I'll take a glance at the fix to see if we can recognize any patterns in sensitive fields, and if not, I'll close this issue 👍
