### ISSUE TITLE
Ruby detection - ruleId ruby.lang.security.create-with.create-with - false positive?

### ISSUE THREAD

**Issue by part-time-githubber** [returntocorp/sgrep-rules#1121]
**Describe the bug**
We are using rails ~> 6.1.1. and it reported ruleId ruby.lang.security.create-with.create-with which seems false positive as per https://vuldb.com/?id.67377

**To Reproduce**
any code piece like 
customer = Customer.create_with(
        some_id: api.same_id
      ).find_or_create_by!(some_id: customer_details.fetch(:same_id))

**Expected behavior**
Do not highlight this as a SAST issue?

**Screenshots**

**What is the priority of the bug to you?**
P2

**Environment**
locally built docker image which does RUN pip3 install semgrep to get the latest on FROM python:3.6-slim AS builder

**Comment by colleend** [comment]
Thanks for filing this issue! 

As you've noted, the _create_with_ issue is fixed after upgrading to Ruby 4.0.9 or 4.1.5. However, semgrep itself can't detect Ruby versions and therefore the check will catch _create_with_ calls despite the Ruby version you are running.

We still want to include this in our Ruby library as we are opting for more thorough checks that will catch most vulnerabilities. Many of our Ruby rules are ported from Brakeman (including this one), which can do versioning checks, but once they come to semgrep the versioning checks are not replicable. 

If you want to run semgrep and don't want the rule to fire on a specific line, you can use
```
# nosemgrep: <ruleid>
```
as specified in https://semgrep.dev/docs/ignoring-findings/#ignoring-findings-via-inline-comments

Hope this was helpful!


Hope this helps, and thanks for letting us know!

**Comment by part-time-githubber** [comment]
many thanks for the quick follow-up. 

i have basic understanding of semgrep working on regexes but was not sure if it can factor in versioning too somehow. 

and yeah, we have managed to silence it with nosemgrep pattern. on a related note, wish the ignoring a sub-directory  feature was available in semgrep cli in addition to ci, for things like unit tests, but as I understand, there is a commercial reasoning to it :-)

**Comment by colleend** [comment]
Thanks so much for your feedback! We'll definitely take this into consideration 😄 

Hmmm, you might actually be able to do something similar with the ```paths``` (include/exclude) key. Here's the [docs](https://semgrep.dev/docs/writing-rules/rule-syntax/#excluding-a-rule-in-paths). We appreciate you taking the time to file an issue!
