### ISSUE TITLE
Query on fixing javascript.browser.security.raw-html-concat.raw-html-concat 

### ISSUE THREAD

**Issue by jithurjacob** [returntocorp/sgrep-rules#1138]
Hi Team,

I am trying to fix an error given by semgrep for javascript.browser.security.raw-html-concat.raw-html-concat. While referring to OWASP I thought using textContent instead of innerText should solve potential XSS. But semgrep still shows the error. Is it because textContent is not a safe method or is it because it was not added to rules?

https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html#rule-6-populate-the-dom-using-safe-javascript-functions-or-properties

```
var liItem = document.createElement("li");
liItem.innerText = `${operation} ${column_name} - ${status}`;
logList.appendChild(liItem);
```

**Comment by jithurjacob** [comment]
@inkz - Could you please help with this query?

**Comment by inkz** [comment]
@jithurjacob I think that you did everything right, the code looks good to me and it should not be highlighted by `javascript.browser.security.raw-html-concat.raw-html-concat` rule
Are you sure that semgrep still shows the same error?
maybe it is pointing to another part of the code?

**Comment by inkz** [comment]
@jithurjacob closing for now, let me know if the error still pops up and I'll reopen the issue.
