### ISSUE TITLE
False positive for react noopener rule

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1158]
**Describe the bug**
I added `noopener` to some links and the rule still fired. See https://github.com/returntocorp/semgrep-app/pull/1840#discussion_r592491698.

**To Reproduce**
See https://github.com/returntocorp/semgrep-app/pull/1840#discussion_r592491698.

**Expected behavior**
Should not fire.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by inkz** [comment]
@minusworld commented on the pull request https://github.com/returntocorp/semgrep-app/pull/1840#discussion_r592889531
