### ISSUE TITLE
detected-artifactory-password: FPs in SVG files

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-rules#1182]
**Describe the bug**

<img width="798" alt="Screen Shot 2021-03-23 at 14 37 53" src="https://user-images.githubusercontent.com/1060436/112155507-a8299080-8be5-11eb-9260-d04cfb7411db.png">

**Comment by minusworld** [comment]
Addressed with https://github.com/returntocorp/semgrep-rules/pull/1184
