### ISSUE TITLE
python.lang.correctness.tempfile.flush.tempfile-without-flush

### ISSUE THREAD

**Issue by aryx** [returntocorp/sgrep-rules#1195]
**Describe the bug**
A clear and concise description of what the bug is and for which rule. Is the rule producing a false positive? Is it incorrect or missing something?

False positive. See

https://github.com/returntocorp/semgrep/pull/2836

**To Reproduce**
Sample code to reproduce this behavior.

**Expected behavior**

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Additional Context**

**Comment by aryx** [comment]
@mschwager already getting benefits in using our policy on our own code!

**Comment by minusworld** [comment]
Fixed by: https://github.com/returntocorp/semgrep-rules/pull/1192

**Comment by mschwager** [comment]
Closing this out as https://github.com/returntocorp/semgrep-rules/pull/1192 is in
