### ISSUE TITLE
typescript.react.security.audit.react-href-var

### ISSUE THREAD

**Issue by sabrinabrogren** [returntocorp/sgrep-rules#1234]
**Describe the bug**
False positive

**To Reproduce**
https://github.com/returntocorp/semgrep-app/pull/1914
![image](https://user-images.githubusercontent.com/15618941/114231689-bf3be280-9948-11eb-9cc8-e2e9c61accbc.png)
The href here is a constant that was imported at the top of the file.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Comment by minusworld** [comment]
A case like this requires crossing "file boundaries" to infer that the `href` variable is a constant string. Perhaps we could use the all caps heuristic... but that might lend itself to false negatives.

We might be able to filter this out with a `join` rule in `0.59`, but I think cases like this might be most easily handled with a `// nosemgrep` exemption for the time being.
