### ISSUE TITLE
[Question] javascript.lang.security.audit.detect-bracket-object-injection integer index access false positive

### ISSUE THREAD

**Issue by ghost** [returntocorp/sgrep-rules#1248]
**Describe the bug**
Whenever arrays are being accessed in Javascript code, the rule picks it up as an object injection vulnerability.
The code below gets flagged for object injection vulnerability because it thinks the value of 0 being used is a taint
```
const a = some_map[0]
```
Is there a pattern syntax that allows us to detect integers being used? So that I can exclude it from the pattern.
eg.
```
const $VAR = $OBJ[integer];
```

**To Reproduce**
See code example

**Expected behavior**
Array access via integer should not be flagged as vulnerability for `javascript.lang.security.audit.detect-bracket-object-injection` rule.

Perhaps some kind of pattern syntax can be used for integers?

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ x ] P2: annoying but not blocking me

**Comment by colleend** [comment]
Thanks for the question! Although there isn't a specific pattern syntax that allows integer detection, you can denote the array index as a metavariable (say, $INT) and use metavariable-regex to specify how '$INT' should look like in regex. 

Here's an example: 
https://semgrep.dev/s/L0L9/?version=0.43.0

The regex I specified states that '$INT' needs to have at least one alphabetical character followed by any number of alphanumeric characters. Hope this helps!

**Comment by ghost** [comment]
Thanks @colleend :) ! Did not see the rule syntax docs as I was focusing on the pattern syntax.
