### ISSUE TITLE
FP on jquery-insecure-method

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1260]
**Describe the bug**
`jquery-insecure-method` matches a normal array `.append(...)`. It should not match this.

**To Reproduce**
https://semgrep.dev/s/704Q/

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by inkz** [comment]
bumped into https://github.com/returntocorp/semgrep/issues/3010 while trying to not match cases with variables from loop declarations

**Comment by inkz** [comment]
done
