### ISSUE TITLE
rule:contrib.nodejsscan.sql_injection.node_sqli_injection is matching graphql

### ISSUE THREAD

**Issue by kenptr** [returntocorp/sgrep-rules#1261]
**Describe the bug**
https://github.com/returntocorp/semgrep-rules/blob/develop/contrib/nodejsscan/sql_injection.yaml

is matching graphql

**To Reproduce**

```
import { gql } from "@apollo/client";

const CURRENT_USER_GQL = gql`
  query currentUser {
    currentUser {
      user_id
      role
    }
  }
`;

const result = await client.query({
        query: CURRENT_USER_GQL,
        fetchPolicy: "network-only",
      });
```

Output:

```
Untrusted input concatinated with raw SQL query can result in SQL Injection.
```

**Expected behavior**
should not match

**Priority**

- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Additional Context**

I use this packages: typescript, @apollo/client

**Comment by minusworld** [comment]
Thanks @kenptr. We've actually switched the `nodejsscan` rules from using the rules in `contrib` to the rules in the original repository, here: https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/database/sql_injection.yaml.

If you have issues, you can file an issue there.

@ajinabraham I tried the latest version of this rule here on the sample code above, and it appears to still match the GraphQL query. https://semgrep.dev/s/BL75/
Let me know if you need any help working on this!

**Comment by ajinabraham** [comment]
I have opened an issue upstream to address this.

**Comment by minusworld** [comment]
Closing on this repository. This issue will be tracked further on https://github.com/ajinabraham/njsscan/issues/72. Thanks all! 👍
