### ISSUE TITLE
generic.secrets.security.detected-facebook-oauth.detected-facebook-oauth matched by github path

### ISSUE THREAD

**Issue by devd** [returntocorp/sgrep-rules#1275]
**Describe the bug**
https://github.com/facebook/zstd/blob/12c045f74d922dc934c168f6e1581d72df983388/doc/zstd_compression_format.md matches the generic.secrets.security.detected-facebook-oauth.detected-facebook-oauth pattern (pattern is "[fF][aA][cC][eE][bB][oO][oO][kK].*['|\"]?[0-9a-f]{32}['|\"]?")

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x ] P2: annoying but not blocking me

**Additional Context**
I think maybe changing .* to [^/]* might be good.

**Comment by minusworld** [comment]
@devd Do you still experience this FP? I tried to match the Markdown file here (https://semgrep.dev/s/Dwqj) but wasn't able to. Thanks!

**Comment by inkz** [comment]
@minusworld Unfortunately, this is not the content of the file but its filename that gets highlighted
https://semgrep.dev/s/2R1q/

**Comment by minusworld** [comment]
:O

Ohh, I see 😅
