### ISSUE TITLE
SQL injection false negative

### ISSUE THREAD

**Issue by emjin** [returntocorp/sgrep-rules#1277]
**Describe the bug**
See https://github.com/returntocorp/semgrep/issues/3065

**Steps to reproduce**
https://semgrep.dev/s/enochii:false-negative-of-sql-injection

The fix seems very easy: the original reporter proposed
![image](https://user-images.githubusercontent.com/5942585/117672897-45319000-b178-11eb-9356-37318c3bac72.png)

To avoid false positives, we might prefer 
`- pattern: $OBJ.Exec("..." + $X + ...)`

Perhaps this is something we need to change for the subsequent patterns as well, however.

**What is the priority of the bug to you?**

P2(regular bug that should get fixed)

**Comment by enochii** [comment]
Hi! So to fix this issue, the changes should be done in original [repo](https://github.com/returntocorp/semgrep/)? Seems like I don't find the corresponding `yaml` file here.

**Comment by inkz** [comment]
Hi @enochii , the rule that need to be fixed is located in this repository (https://github.com/returntocorp/semgrep-rules/)
here is the file: https://github.com/returntocorp/semgrep-rules/blob/develop/go/lang/security/audit/database/string-formatted-query.yaml
:pray: sorry for the long response.
