### ISSUE TITLE
False positive in generic.nginx.security.missing-internal.missing-internal

### ISSUE THREAD

**Issue by sk-** [returntocorp/sgrep-rules#1282]
**Describe the bug**
The patterns for `generic.nginx.security.missing-internal.missing-internal` match any configuration using `proxy_pass`, even it it doesn't allow SSRF.

**To Reproduce**
```
location / {
        proxy_pass http://127.0.0.1:8000/;
}
```

**Expected behavior**
This should not raise an error.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [X] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Additional Context**
Based on the linked article https://github.com/yandex/gixy/blob/master/docs/en/plugins/ssrf.md it seems that there may be a vulnerability in case the proxy_pass location is not constant.

**Comment by inkz** [comment]
Thanks a lot for noticing this @sk- !
link to the commit: https://github.com/returntocorp/semgrep-rules/pull/1320
