### ISSUE TITLE
Secure Session Cookies

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#130]

**Comment by minusworld** [comment]
https://flask.palletsprojects.com/en/1.1.x/security/#set-cookie-options

**Comment by minusworld** [comment]
https://github.com/returntocorp/sgrep-rules/pull/193

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/score/630?check_id=sgrep-rules.python.flask.secure-cookies.secure-session-cookies

**Comment by minusworld** [comment]
Needs to filter out patterns where config is loaded from file:
`app.config.from_object(config)`
