### ISSUE TITLE
jinja unescaped template string (building templates on the fly)

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#131]
Already done in https://github.com/returntocorp/bento-core/issues/328 but can we do in sgrep?

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/jobs/585?page=1&sort_on=repo_url&sort_by=asc

**Comment by minusworld** [comment]
https://github.com/returntocorp/sgrep-rules/pull/203
