### ISSUE TITLE
Incorrect Rule Documentation in java-jwt-none-alg

### ISSUE THREAD

**Issue by testation21** [returntocorp/sgrep-rules#1332]
**Describe the bug**
In a rule, java-jwt-none-alg, document, there are several examples on it.
However, there is an incorrect example in the examples.
The incorrect example:
````
abstract class App2{
    static String secret = "secret";

    public void bad2() {
        try {
            Algorithm algorithm = Algorithm.HMAC256(secret);
            String token = JWT.create()
                .withIssuer("auth0")
                .sign(algorithm);
        } catch (JWTCreationException exception){
            //Invalid Signing configuration / Couldn't convert Claims.
        }
    }

}
````
This example is related to a rule, java-jwt-hardcoded-secret.
It is better to remove the example to clarify the rule description.
It is not that big problem, also, I think it could be modified easily.

Please, check this case.
Thank you for your consideration.

**To Reproduce**
https://semgrep.dev/r?q=java-jwt-none-alg

**Expected behavior**
Do not show an incorrect example for java-jwt-none-alg rule.

**Priority**
P2: annoying but not blocking me

**Comment by inkz** [comment]
Thank you @testation21!
