### ISSUE TITLE
Update rules to move away from features only available with `--optimizations none`

### ISSUE THREAD

**Issue by brendongo** [returntocorp/sgrep-rules#1365]
**Is your feature request related to a problem? Please describe.**
A lot of the recent improvements in semgrep performance are only available when
it can run with optimizations but there is some functionality unavailable and when those
functionality is detected, semgrep falls back to running without optimizations.

This includes the following:
- pattern-where-python
- equivalences
- taint mode

We should update our rules to be able to run with optimizations as much as possible.

- There are four rules running pattern-where-python
    - https://github.com/returntocorp/semgrep-rules/blob/develop/contrib/dlint/redos.yaml
    - https://github.com/returntocorp/semgrep-rules/blob/develop/go/gorilla/security/audit/handler-attribute-read-from-multiple-sources.yaml
    - https://github.com/returntocorp/semgrep-rules/blob/develop/python/flask/experimental/correctness/different-route-names.yaml
    - https://github.com/returntocorp/semgrep-rules/blob/develop/python/lang/security/audit/insecure-file-permissions.yaml
- There is the one rule running equivalences
    - https://github.com/returntocorp/semgrep-rules/blob/develop/java/lang/correctness/no-string-eqeq.yaml 
- There are no rules running taint mode

The equivalence rule seems easy enough to rewrite but not the pattern-where-python rules. Should we be implementing some scheme to support something similar with optimizations all or can we go without these rules?

# When is work done

- [ ] When no r2c official rulesets contain rules that need experimental features listed above

**Comment by mschwager** [comment]
Perhaps we should remove `equivalences` instead: https://github.com/returntocorp/semgrep/issues/3049

**Comment by brendongo** [comment]
Yeah definitely going to remove equivalences from semgrep this ticket is to remove it's use in our rules.

**Comment by brendongo** [comment]
Relevant https://github.com/returntocorp/semgrep/pull/3493

**Comment by inkz** [comment]
@minusworld @mschwager @brendongo 
Updated the rule with `equivalences`

speaking of `pattern-where-python` rules, I was not able to convert most of them,

https://github.com/returntocorp/semgrep-rules/blob/develop/python/lang/security/audit/insecure-file-permissions.yaml
this one  looks resolvable, just need more time on it

https://github.com/returntocorp/semgrep-rules/blob/develop/contrib/dlint/redos.yaml
Redos rule is just basically one big python script placed in a semgrep YAML file, so I am pretty sure we not gonna be able to somehow convert it

https://github.com/returntocorp/semgrep-rules/blob/develop/go/gorilla/security/audit/handler-attribute-read-from-multiple-sources.yaml
https://github.com/returntocorp/semgrep-rules/blob/develop/python/flask/experimental/correctness/different-route-names.yaml
this two could work without `pattern-where-python` if we had `metavariable-comparison` for strings (is it planned?)

**Comment by brendongo** [comment]
Do we have the last four rules in any rulesets even? If we remove them from the rulesets (we're ok with not having these rules anymore) we can just remove them instead of trying to fix?

**Comment by brendongo** [comment]
Hmm looks like handler-attribute-read-from-multiple-sources might be the only rule in public rulesets.

**Comment by minusworld** [comment]
That one can be deleted, as well - when I last checked a week ago, it has never fired

**Comment by minusworld** [comment]
I'll remove `handler-attribute-read-from-multiple-sources` and `different-route-names` shortly

**Comment by brendongo** [comment]
With above PRs I think it's fine to move the deprecation notice in this release
