### ISSUE TITLE
Many rules have hard-coded line breaks in messages, resulting in poor terminal display

### ISSUE THREAD

**Issue by huonw** [returntocorp/sgrep-rules#1431]
**Describe the bug**

Many rules have messages that include literal line-breaks, which results in poor display in a terminal. This is usually because the message field is configured with `|`. For instance, the following two code blocks are equivalent:

```yaml
message: |
   Some message here
...
message: |
   Some wrapped 
   message
```

```yaml
message: "Some message here\n"
...
message: "Some wrapped\nmessage\n"
```

(Note the trailing line break too.)

https://yaml-multiline.info has more info/description.

Arguably this is a bug in semgrep itself, which could strip out the newlines from the messages.

**To Reproduce**

Run any rule that contains a message configured with `|`, like https://github.com/returntocorp/semgrep-rules/blob/e6c956f4fc5832594e6e8ff89123726c8e54ec6c/yaml/semgrep/missing-message-field.yaml#L3-L7

```shell
semgrep -c yaml/semgrep/missing-message-field.yaml yaml/semgrep/missing-message-field.test.yaml                 
```
```
running 1 rules...
yaml/semgrep/missing-message-field.test.yaml
severity:warning rule:yaml.semgrep.missing-message-field: This rule does not have a message. Semgrep requires that
rules have a message. Include a message to explain what the rule does.
Consider writing a message that explains why this is an issue and
how to fix it.

3:- id: unchecked-subprocess-call
ran 1 rules on 1 files: 1 findings
```

Note the rule description is:

1. broken across multiple lines, exactly matching the file configuration
2. has an extra blank line after the definition

This is even worse when using flags like `--vim` or `--emacs`, that are explicitly documented as outputting in a "single-line" format, as the message still breaks across multiple lines.

```shell
semgrep --vim -c yaml/semgrep/missing-message-field.yaml yaml/semgrep/missing-message-field.test.yaml  
```

```
running 1 rules...
yaml/semgrep/missing-message-field.test.yaml:3:3:W:yaml.semgrep.missing-message-field:This rule does not have a message. Semgrep requires that
rules have a message. Include a message to explain what the rule does.
Consider writing a message that explains why this is an issue and
how to fix it.

ran 1 rules on 1 files: 1 findings
```

**Expected behavior**

Messages should almost always be displayed on a single line, especially when using the `--vim`/`--emacs` format.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser n/a
 - Version n/a
- Semgrep version: 0.61.0

**Additional context**

**Comment by ievans** [comment]
Big +1 to this for me, my vote would be that we refactor this repo and enforce going forward & possibly as a semgrep metacheck.

**Comment by huonw** [comment]
Thanks for the quick response! I've opened a PR with a potential rule #1432.

**Comment by brendongo** [comment]
Would also be supportive of having semgrep strip leading and trailing endlines. Can't really think of why they would ever need to be there.

**Comment by emjin** [comment]
Love the meta-rule! I do agree that having semgrep strip newlines may be even better though. The new lines exist for PR readability. Can be persuaded otherwise if there are convincing places where people may want messages to preserve their new line choices.

**Comment by huonw** [comment]
For manual formatting/readability, the `>-` block scalar header allows retaining the hard-wrapped lines without them coming through in the final string (`>-` collapses whitespace, while `|` retains them as written), https://yaml-multiline.info goes through the rather proliferation of options here. (I may be misunderstanding your point, though.)

(I definitely agree that having semgrep strip them automatically would be less error-prone/more friendly than the meta-rule.)

**Comment by minusworld** [comment]
Addressed by https://github.com/returntocorp/semgrep-rules/pull/1432
