### ISSUE TITLE
owasp-top-ten rule file not being pulled

### ISSUE THREAD

**Issue by harshkolhatkar** [returntocorp/sgrep-rules#1444]
**Describe the bug**
The owasp-top-ten rule file is not getting curl'ed properly. Returns the html content instead.

**To Reproduce**
1. Run the following command `curl -k -L -H 'User-Agent: Semgrep/0.27' https://semgrep.dev/p/owasp-top-ten > owasp.yaml`
2. owasp.yaml has html content in it,
![image](https://user-images.githubusercontent.com/36478006/131357372-e1b4ae32-9446-4e73-bf9f-e6b156ad8b57.png)

**Expected behavior**
Whereas, any other pull of config files gives back the yaml content,
![image](https://user-images.githubusercontent.com/36478006/131356766-89f33bea-89c4-43f7-935f-cb86e03e0d71.png)

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Desktop (please complete the following information):**
 - CentOS 7

**Comment by minusworld** [comment]
🤔  Strange. If I run the same command on Mac OS, it comes back as YAML:

```
➜  ~ curl -k -L -H 'User-Agent: Semgrep/0.27' https://semgrep.dev/p/owasp-top-ten | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    325      0 --:--:-- --:--:-- --:--:--   324
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0rules:
- id: csharp.lang.security.injections.os-command.os-command-injection
  severity: WARNING
  languages:
  - C#
  metadata:
    cwe: 'CWE-78: Improper Neutralization of Special Elements used in an OS Command
      (OS Command Injection)'
    owasp: 'A1: Injection'
    references:
```

@harshkolhatkar Is it possible that you're behind a proxy that might be stripping headers? 🤔 
In the meantime, you can explicitly request YAML without the header by adding a `c` into the URL: https://semgrep.dev/c/p/owasp-top-ten.

**Comment by minusworld** [comment]
Let me know if you're still unable to get the `p/owasp-top-ten` YAML and I or someone will figure out the deeper issue.

**Comment by harshkolhatkar** [comment]
> 🤔 Strange. If I run the same command on Mac OS, it comes back as YAML:
> 
> ```
> ➜  ~ curl -k -L -H 'User-Agent: Semgrep/0.27' https://semgrep.dev/p/owasp-top-ten | head
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   138  100   138    0     0    325      0 --:--:-- --:--:-- --:--:--   324
>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0rules:
> - id: csharp.lang.security.injections.os-command.os-command-injection
>   severity: WARNING
>   languages:
>   - C#
>   metadata:
>     cwe: 'CWE-78: Improper Neutralization of Special Elements used in an OS Command
>       (OS Command Injection)'
>     owasp: 'A1: Injection'
>     references:
> ```
> 
> @harshkolhatkar Is it possible that you're behind a proxy that might be stripping headers? 🤔
> In the meantime, you can explicitly request YAML without the header by adding a `c` into the URL: https://semgrep.dev/c/p/owasp-top-ten.

Yeah, I'm from inside the corporate network so there's a possibility the headers are getting stripped. 
Thanks! That pulls up the yaml file. Now, does the /c/p/config.yaml URL apply to all files?

**Comment by minusworld** [comment]
> Yeah, I'm from inside the corporate network so there's a possibility the headers are getting stripped.
> Thanks! That pulls up the yaml file. Now, does the /c/p/config.yaml URL apply to all files?

Great news!

Yes, `/c/p/<config>` will work for all configs. 👍
