### ISSUE TITLE
Rewrite python `insecure-file-permissions`

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1445]
**Describe the bug**
A few people have expressed interest in running https://semgrep.dev/editor?registry=python.lang.security.audit.insecure-file-permissions.insecure-file-permissions which is still available in the registry (because it does not sync deletions with this repository). This rule uses `pattern-where-python`, which was deprecated.

This rule needs to be updated.

**To Reproduce**
https://semgrep.dev/editor?registry=python.lang.security.audit.insecure-file-permissions.insecure-file-permissions

**Expected behavior**

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by elb-slack** [comment]
Thank you!
