### ISSUE TITLE
Broken Rule Set Link

### ISSUE THREAD

**Issue by paisleyrob** [returntocorp/sgrep-rules#1488]
**Describe the bug**
The `README.md` link "list of repositories with Semgrep rules" is broken. See link to the offending line below. I didn't see a way to get directly to the line without using blame.

https://github.com/returntocorp/semgrep-rules/blame/develop/README.md#L28

**Expected behavior**

I expected to find a link that worked and described how the rule sets are created. My goal is an entirely offline version of these rules which closely follows this repository in an entirely offline environment.

**Additional context**

Digging into the `semgrep` code I've determined how to download the rulesets, but I'd prefer if I could build these rulesets locally from just the repository contents rather than trusting that each time I download it I get the same content(s).

`curl --location --user-agent Semgrep/0.65.0 https://semgrep.dev/p/security-audit > security-audit.yaml`

**Comment by paisleyrob** [comment]
Acording to this from slack: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1632422404079900 rule sets are from a private repository `semgrep-rule-packs`.

Could the README.md reflect that so no one else spends time searching for the rule sets?

**Comment by minusworld** [comment]
@paisleyrob Thanks for your comments. I don't think I ever would have remembered to check those links. (Maybe I'll add a CI job to check links.)

Anyway... does https://github.com/returntocorp/semgrep-rules/pull/1545 look like it addresses your comments here? Thanks!

Happy to work with you to update anything else on the README, too. 😄

**Comment by paisleyrob** [comment]
#1545 appears to address my comments. Thanks!
