### ISSUE TITLE
[Rule] Lua: wrong java.lang.correctness.eqeq.eqeq exception

### ISSUE THREAD

**Issue by stuta** [returntocorp/sgrep-rules#1489]
In lua line `if name == nil or name == "" then` causes java.lang.correctness.eqeq.eqeq exception. It should not cause that exception.

**Comment by minusworld** [comment]
Hey @stuta , thanks for filing an issue! Could you provide an example of the issue you're experiencing?

You can also use https://semgrep.dev/editor to create a shareable link. Click the `Share` button in the top right and paste your example in here.

Thanks again!

**Comment by stuta** [comment]
This is the example:

```lua
local name
if name == nil or name == "" then -- semgrep causes java.lang.correctness.eqeq.eqeq exception  here, it should not
end
```

**Comment by minusworld** [comment]
@stuta What is the command you are using to run Semgrep? Are you using it locally or in CI?

I'm unable to get Java rules to work on Lua files.

Example: https://semgrep.dev/s/XO7w

On the CLI:

```
➜  lua ls
something.lua
➜  lua cat something.lua
local name
if name == nil or name == "" then -- semgrep causes java.lang.correctness.eqeq.eqeq exception  here, it should not
end%
➜  lua semgrep -f r/java
Fetching rules from https://semgrep.dev/registry ...
Running 262 rules...
100%|██262/262
ran 262 rules on 1 files: 0 findings
```

**Comment by stuta** [comment]
I’m using vscode extension in osx.

**Comment by stuta** [comment]
Here is a screenshot:

![Näyttökuva 2021-10-17 kello 16 03 51](https://user-images.githubusercontent.com/1422999/137628345-de6a7736-4745-41b5-9975-b81f7e3b50ff.png)

**Comment by minusworld** [comment]
OK, I can reproduce if I target it directly, and I would guess the VSCode extension runs something similar `semgrep --config r/javascript.lang.correctness.useless-eqeq something.lua`

**Comment by minusworld** [comment]
I've filed a bug for this over on the Semgrep repo: https://github.com/returntocorp/semgrep/issues/4157
