### ISSUE TITLE
using url_for to lookup an invalid blueprint view only crashes at runtime when you access a page using it that reference to the invalid blueprint view

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#151]

**Comment by mschwager** [comment]
If this is referencing using `url_for` in a template file, then I think detecting this behavior will be a relatively large chunk of work, and may not be feasible with `sgrep`. Connecting templates to their Python code will require analyzing the filesystem (i.e. does a template used in Python code exist? does a blueprint used in a template exist in Python code?). It'll also require connecting Python static analysis information with templates available, and parsing `url_for` information from a template and connecting it with Python static analysis information.

It's certainly doable! But it feels like a large task to me.

**Comment by minusworld** [comment]
Yeah.

You can call `url_for` on blueprints both in Python and the templates. I'm going to attempt the Python version first, which I think will be much easier!

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/jobs/655?page=1&sort_on=repo_url&sort_by=asc

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/score/662?check_id=r2c-flask-blueprint-does-not-exist

Precision is not high... 25%. I fixed everything I could on it but don't think it's worth pursuing any further in flake8.

**Comment by minusworld** [comment]
If we truly want to implement this in the future -- and I think it's a great check based on what was found -- we should build our own runner or implement a new Tool in Bento.

**Comment by minusworld** [comment]
btw this lives in https://github.com/returntocorp/r2c-checks/tree/blueprint-does-not-exist
