### ISSUE TITLE
[Ruby] Hardcoded file paths into deserialization functions

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1524]
**Describe the bug**
Filter out cases of static strings from `File.open(...)` to deserialization functions like `YAML.load(...)`.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by colleend** [comment]
👋  do you mean `File.read(...)` in this case?
