### ISSUE TITLE
generic.dockerfile.correctness.alias-must-be-unique.alias-must-be-unique

### ISSUE THREAD

**Issue by sfc-gh-ssikdar** [returntocorp/sgrep-rules#1531]
**Describe the bug**
A clear and concise description of what the bug is and for which rule. Is the rule producing a false positive? Is it incorrect or missing something?

In regression test file it is incorrectly pointing to a valid SQL query. I would classify this as false positive.

**To Reproduce**
Sample code to reproduce this behavior.

**Expected behavior**

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Additional Context**

**Comment by colleend** [comment]
Thanks for filing this issue! Would it be possible to post a few lines of anonymized code from the regression test file so that we can test this? Also what SQL rule is flagging?
