### ISSUE TITLE
Registering different routes with the same endpoint name (the function name by default). This will raise a runtime error but could be linted sooner.

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#156]

**Comment by ulziibay** [comment]
I dont think this is doable in Sgrep because we need to keep track of a state for all route definitions we see and then alert on duplicates

**Comment by minusworld** [comment]
Could we approximate with something like

```
@app.route("...")
def $R(...):
    ...
...
@app.route("...")
def $R(...):
    ...
```

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/filter/630?check_ids=sgrep-rules.python.flask.flask-duplicate-handler-name
