### ISSUE TITLE
Duplicated Rulesets

### ISSUE THREAD

**Issue by paisleyrob** [returntocorp/sgrep-rules#1595]
**Describe the bug**
https://semgrep.dev/r's rulesets list 51 rule sets but there are only 49 distinct rule sets. The set "test" and the set "sql-injection" are duplicated.

**Comment by minusworld** [comment]
Thanks @paisleyrob - there's a known issue on the webapp where deletions are not being synced correctly, so sometimes there end up being duplicates. I've added this issue to the internal issue for this problem. Thanks!
