### ISSUE TITLE
[Rule] Detect hardcoded secrets in code 

### ISSUE THREAD

**Issue by roisec** [returntocorp/sgrep-rules#1607]
Hi
**Rule Description**
Detect hardcoded secrets in code, passwords, tokens and etc.
*What does this rule intend to find?*
Hardcoded password/secrets in code
**Examples or references**
DB_PASSWORD=,*_PASSWORD=,*_token=,API_KEY=

I can create a pull request if you agree with this ..
Thanks

**Comment by minusworld** [comment]
Hey @RoiSec! We are always accepting pull requests. Check out our [contributing guidelines](https://github.com/returntocorp/semgrep-rules/blob/develop/CONTRIBUTING.md) for the best way to make a submission.

For secrets rules, we hope to see some examples of what it should find (but not actual secrets!) and some examples of what it should not find.

In addition, we do have some [secrets rules already](https://semgrep.dev/p/secrets). Many of them are regular expressions which scan for common secret patterns. However, we also have some that check for hardcoded secrets in code such as https://semgrep.dev/r?q=python.boto3.security.hardcoded-token.hardcoded-token.

Looking forward to your contribution!

Thanks!
