### ISSUE TITLE
md5-used-as-password incorrectly recommends SHA256 as alternative

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#1609]
* [semgrep-rules/md5-used-as-password.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/php/lang/security/md5-used-as-password.yaml)
* [semgrep-rules/md5-used-as-password.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/ruby/lang/security/md5-used-as-password.yaml)
* [semgrep-rules/md5-used-as-password.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/go/lang/security/audit/md5-used-as-password.yaml)
* [semgrep-rules/md5-used-as-password.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/java/lang/security/audit/md5-used-as-password.yaml)
* [semgrep-rules/md5-used-as-password.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/python/lang/security/audit/md5-used-as-password.yaml)
* [semgrep-rules/md5-used-as-password.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/md5-used-as-password.yaml)

> It looks like MD5 is used as a password hash. MD5 is not considered a secure password hash because it can be cracked by an attacker in a short    amount of time. Use SHA-256 or higher for password hashes (for example: `hash('sha256', ...)`)

The recommendation, *Use SHA-256 or higher for password hashes*, is incorrect. 
SHA256 is also not a proper password hashing function, as it is too fast. Acceptable hash functions are PBKDF2, bcrypt, scrypt, argon2. Most languages/frameworks have a supported password hashing function, we should recommend that. E.g. for PHP there's [password_hash](https://www.php.net/password_hash).

**Comment by Sjord** [comment]
These seem to be the proper recommendations:

* PHP: [password_hash](https://www.php.net/password_hash)
* ruby: [bcrypt](https://rubygems.org/gems/bcrypt), optionally through [rails](https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html).
* go: [bcrypt](https://pkg.go.dev/golang.org/x/crypto/bcrypt)
* java: [Spring PasswordEncoder](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/PasswordEncoder.html), or PBKDF2 with PBEKeySpec and SecretKeyFactory.
* python: [hashlib.scrypt](https://docs.python.org/3/library/hashlib.html#hashlib.scrypt), [passlib](https://pypi.org/project/passlib/)
* javascript: [bcrypt](https://www.npmjs.com/package/bcrypt)

**Comment by minusworld** [comment]
@Sjord Thanks for finding the proper libs! That's way above and beyond and makes editing the rule much easier. :D 

Someone will get to this change in the next few days. Thank you so much!

**Comment by minusworld** [comment]
@Sjord - I made https://github.com/returntocorp/semgrep-rules/pull/1627. Does this look good to you?

Also, I personally found your summary of libraries for each language extremely informative. Would you mind if we turned these into some kind of cheatsheet for a blog or for semgrep.dev/docs? (Or are you interested in making one yourself?)

**Comment by Sjord** [comment]
Thank you, looks good. Feel free to use the summary in any way.
