### ISSUE TITLE
Ignore example keys for generic.secrets.security.detected-aws-access-key-id-value.detected-aws-access-key-id-value

### ISSUE THREAD

**Issue by pm98zz-c** [returntocorp/sgrep-rules#1620]
The rule for detecting AWS keys flags "examples" keys, typically in README.md files, giving false positives. I'd suggest the
rule could be amended to NOT flag keys containing "EXAMPLE" in them.
Maybe a few others exceptions, too (SAMPLE, YOURKEY, YOURSECRET) ?

I haven't checked for other rules in the generic.secrets, but I suspect others would be affected too.

**Comment by minusworld** [comment]
Thanks @pm98zz-c! I made https://github.com/returntocorp/semgrep-rules/pull/1628. Does this look like it fixes your issue?

**Comment by pm98zz-c** [comment]
@minusworld Yes, it does. Thanks.

**Comment by pm98zz-c** [comment]
Rethinking a bit more about it, I might be making noise for nothing here. I did have a look at the other rules in generic.secrets, and they would more or less ALL need amending if we follow my suggestion.
Given that most follow a given pattern anyway, it should be relatively easy for users to amend their examples in a way that does not match.

In a nutshell, my suggestion probably is a "false good idea" and should be ignored, I'm afraid, too much work for the convenience. So unless you (or others) think otherwise, happy for the issue to be closed and ignored.

Sorry for not realizing before you made the change, had not fully thought through the fact all rules would have to follow.
