### ISSUE TITLE
[Rule] PHP : Validate openssl_decrypt return value is assigned to variable 

### ISSUE THREAD

**Issue by thotakartheek004** [returntocorp/sgrep-rules#1749]
**Rule Description**
OpenSSL decrypt function returns string in case of decrypt success and  returns false in case of failure.
We need to make sure that return value is not false , if it's false we need to handle it.
If its not handled , there can be chances of processing ahead even in case of decryption failure
Making sure that openssl_decrypt variable is assigned to variable and validated with result and take action if it is false

*What does this rule intend to find?*
Making sure that openssl_decrypt variable is assigned to variable and validated with result and take action if it is false

**Examples or references**

###### Example 1: 

Below code would be issue, where openssl_decrypt function returned false and is not validated which result in processing even in case of decrypt failure 
```
function doSomeAction(){
    $data = openssl_decrypt ( $crypt , "AES-128-CBC" , $key, 0, $iv );
    // Some business logic  and considers as success
}
```
###### Example 2: 

Below code is good practice, where openssl_decrypt function returned false and is validated which avoids execution in case of decrypt failure 
```
function doSomeAction(){
    $data = openssl_decrypt ( $crypt , "AES-128-CBC" , $key, 0, $iv );
    if($data === false){
          ...
          /// Exiting/throwing exception in case of decryption failure
    }
    // Some business logic  and considers as success only when decrypt passes
}
```

*References*

[PHPNET] (https://www.php.net/manual/en/function.openssl-decrypt.php)
**Additional information**
Rule link : https://semgrep.dev/s/thotakartheek004:openssl_decrypt_validate

*More information that would help someone write this rule!*

**PR Checklist**
- [x] This ticket has links, references, or examples.
- [x] The rule has **true positive** and **true negative** test cases in a file that matches the rule name.

> If the rule is `my-rule`, the test file name should be `my-rule.js`.
>
> True positives are marked by comments with `ruleid: <my-rule>` and true negatives are marked by comments with `ok: <my-rule>`.

- [x] The rule has a good message. A good message includes:

> 1. A description of the pattern (e.g., missing parameter, dangerous flag, out-of-order function calls).
> 1. A description of why this pattern was detected (e.g., logic bug, introduces a security vulnerability, bad practice).
> 1. An alternative that resolves the issue (e.g., use another function, validate data first, discard the dangerous flag).

- [ ] After the PR has been reviewed and approved, merge the rule and close this ticket! Thanks for contributing!

**Comment by minusworld** [comment]
@thotakartheek004 I made a PR for this rule here: https://github.com/returntocorp/semgrep-rules/pull/1755

Does it look good to you?
