### ISSUE TITLE
ocaml.lang.best-practice.ref.ocamllint-ref-incr uses incorrect pattern

### ISSUE THREAD

**Issue by sim642** [returntocorp/sgrep-rules#1762]
**Describe the bug**
The current pattern for the rule is `$X := $X + 1`, but that's now OCaml `ref` and `:=` work. The current test for it `x := x + 1` isn't even well-typed! If `$X` is a ref to be assigned, then on the right-hand side it needs to be dereferenced as `!$X`.
For some reason the rule `$X := !$X + 1` doesn't find anything though.

**To Reproduce**
https://semgrep.dev/s/DyQP

**Expected behavior**
The rule should have the pattern `$X := !$X + 1` and it should find the match.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by mjambon** [comment]
Thanks. It's nice to see someone using OCaml :-)

The problem is what you describe, we just need a space between `!` and `$` because `!$` is a valid OCaml operator.
https://semgrep.dev/s/8g9E
