### ISSUE TITLE
Convert `generic.dockerfile` rules to use Dockerfile parser

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1793]
**Is your feature request related to a problem? Please describe.**
Dockerfile support was released in Semgrep recently. Current Dockerfile rules use `generic` mode. This leads to issues like https://github.com/returntocorp/semgrep/issues/4642 and others.

**Describe the solution you'd like**
Switch Dockerfile rules to use the Dockerfile parser.

In `generic/dockerfile/`, the following rules need to be updated:

- [x] avoid-apk-upgrade.yaml
- [x] avoid-apt-get-upgrade.yaml
- [x] avoid-dnf-update.yaml
- [x] avoid-latest-version.yaml
- [x] avoid-platform-with-from.yaml
- [x] avoid-yum-update.yaml
- [x] avoid-zypper-update.yaml
- [x] maintainer-is-deprecated.yaml
- [x] missing-apk-no-cache.yaml
- [x] missing-dnf-assume-yes-switch.yaml
- [x] missing-dnf-clean-all.yaml
- [x] missing-image-version.yaml
- [x] missing-no-install-recommends.yaml
- [x] missing-pip-no-cache-dir.yaml
- [x] missing-yum-assume-yes-switch.yaml
- [x] missing-yum-clean-all.yaml
- [x] missing-zypper-clean.yaml
- [x] missing-zypper-no-confirm-switch.yaml
- [x] nonsensical-command.yaml
- [x] prefer-apt-get.yaml
- [x] prefer-copy-over-add.yaml
- [x] prefer-json-notation.yaml
- [x] remove-package-cache.yaml
- [x] remove-package-lists.yaml
- [x] set-pipefail.yaml
- [ ] use-absolute-workdir.yaml
- [x] use-either-wget-or-curl.yaml
- [x] use-shell-instruction.yaml
- [x] use-workdir.yaml
- [ ] alias-must-be-unique.yaml
- [ ] copy-from-own-alias.yaml
- [x] invalid-port.yaml
- [x] missing-assume-yes-switch.yaml
- [x] multiple-cmd-instructions.yaml
- [x] multiple-entrypoint-instructions.yaml
- [x] last-user-is-root.yaml
- [x] missing-user.yaml

**Comment by 0xDC0DE** [comment]
Working on this in branch `generic-to-dockerfile` https://github.com/returntocorp/semgrep-rules/tree/generic-to-dockerfile

**Comment by 0xDC0DE** [comment]
Skipping use-absolutworkdir.yaml for now.
Blocked by what I think is a bug: https://github.com/returntocorp/semgrep/issues/4866

**Comment by 0xDC0DE** [comment]
I think matching an alias is currently not possible.
Skipping alias-must-be-unique.yaml and copy-from-own-alias.yaml
confirmed. Blocked by: https://github.com/returntocorp/semgrep/issues/4881

**Comment by 0xDC0DE** [comment]
I think the value of `EXPOSE` is not properly parsed as an integer and hence the value can not be used in `metavariable-comparison`. 
Skipping invalid-port.yaml because I think it is blocked by: https://github.com/returntocorp/semgrep/issues/4875
