### ISSUE TITLE
Incorrect description in missing-noreferrer

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#1802]
The description in [semgrep-rules/missing-noreferrer.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/html/security/missing-noreferrer.yaml) is incorrect:

      This anchor tag with 'target="_blank"' is missing 'noreferrer'.
      A page opened with 'target="_blank"' can access the window object of the origin page.
      This means it can manipulate the 'window.opener' property, which could redirect the origin page to a malicious URL.
      This is called reverse tabnabbing. To prevent this, include 'rel=noreferrer' on this tag.

This is just the description of [missing-noopener](https://github.com/returntocorp/semgrep-rules/blob/develop/html/security/missing-noopener.yaml), but with `opener` replaced by `referer`. This is incorrect. `noopener` indeed protects against exposing the `window.opener`, but `noreferer` does not. It prevents exposing the URL of the current page to the newly opened page.

**Comment by Sjord** [comment]
[This page](https://mathiasbynens.github.io/rel-noopener/) and [CWE-1022](https://cwe.mitre.org/data/definitions/1022.html) indicate that `noreferrer` also disables the `window.opener` value, and in Chrome and Opera that indeed seems to be the case. This is probably why two rules are created, one that checks for noopener and one that checks for noreferrer. But that's incorrect; either attribute solves this issue, but according to semgrep you need both attributes.

**Comment by kurt-r2c** [comment]
Resolved by #1910. Old rules will still be present in the [semgrep.dev](https://semgrep.dev) registry pending support for rule deletion - users should adopt `missing-noopener-or-noreferrer` if they want the "latest and greatest" version of this check.
