### ISSUE TITLE
CWE check rule works incorrect

### ISSUE THREAD

**Issue by cyrusmatsumori** [returntocorp/sgrep-rules#1845]
**Describe the bug**
Rule yaml.semgrep.metadata-cwe.yaml work incorrect.
It find violation where it shouldn't be (see description below).

**To Reproduce**
1. Use [yaml.semgrep.metadata-cwe.yaml](https://github.com/returntocorp/semgrep-rules/blob/develop/yaml/semgrep/metadata-cwe.yaml) rule to check all rules in this (returntocorp/semgrep-rules) repo. Run:
```
semgrep --config=semgrep-rules/yaml/semgrep/metadata-cwe.yaml semgrep-rules
```
2. You'll receive few findings:

```
semgrep-rules/javascript/express/security/audit/express-cookie-settings.yaml
severity:error rule:semgrep-rules.yaml.semgrep.metadata-cwe: $...CWE The cwe tag in rule metadata should always be in the format "CWE-000: Title".
10:    cwe: 'CWE-522: Insufficiently Protected Credentials'
--------------------------------------------------------------------------------
43:    cwe: 'CWE-522: Insufficiently Protected Credentials'
--------------------------------------------------------------------------------
94:    cwe: 'CWE-522: Insufficiently Protected Credentials'
--------------------------------------------------------------------------------
146:    cwe: 'CWE-522: Insufficiently Protected Credentials'
--------------------------------------------------------------------------------
197:    cwe: 'CWE-522: Insufficiently Protected Credentials'
--------------------------------------------------------------------------------
248:    cwe: 'CWE-522: Insufficiently Protected Credentials'

semgrep-rules/typescript/react/security/audit/react-dangerouslysetinnerhtml.yaml
severity:error rule:Users.s.burakov.Github.semgrep-rules.yaml.semgrep.metadata-cwe: $...CWE The cwe tag in rule metadata should always be in the format "CWE-000: Title".
11:    cwe: "CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
```

**Expected behavior**
These findings should not appear, because it fits in pattern:
```
pattern-not-regex: CWE-[\d]+:\s+\w
```

Futhermore, there are more than 700 rules with CWE in this repo, which have exact the same correct pattern and metadata-cwe.yaml rule don't appear them as violated.

**Priority**
How important is this to you?
- [x] P2: annoying but not blocking me

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Version 0.83.0

**Additional context**

**Comment by 0xDC0DE** [comment]
I can not reproduce this. @cyrusmatsumori can you check your semgrep version and the branch you were on in this repository?

For me the output is as expected: only one file is detected, the test file for this rule.

```zsh
Findings:

  yaml/semgrep/metadata-cwe.test.yaml
     yaml.semgrep.metadata-cwe
        $...CWE The cwe tag in rule metadata should always be in the format "CWE-000: Title".


         17┆ cwe: "CWE123: Some Vulnerability"
          ⋮┆----------------------------------------
         25┆ cwe: "cwe-123: Some Vulnerability"
          ⋮┆----------------------------------------
         33┆ cwe: CWE-123

Some files were skipped.
  Scan was limited to files tracked by git.
  Scan skipped: 1 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1 rule on 1309 files: 3 findings.
```

**Comment by kurt-r2c** [comment]
@pieterdc1 I also cannot reproduce this.  It's possible that there was a bug either in the rule or engine that has since been fixed.  We should close this and reopen in the future if the problem resurfaces.
