### ISSUE TITLE
go.lang.security.audit.sqli.pg-orm-sqli.pg-orm-sqli false positive

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#1864]
**Describe the bug**
`go.lang.security.audit.sqli.pg-orm-sqli.pg-orm-sqli` matches on `filepath.Join`, which is a false positive.

**To Reproduce**
https://semgrep.dev/s/oyp7

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by kurt-r2c** [comment]
Fixed by #1909
