### ISSUE TITLE
Update javascript non-constant-sql-query 

### ISSUE THREAD

**Issue by 0xDC0DE** [returntocorp/sgrep-rules#1980]
https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/non-constant-sql-query.yaml

This should probably be rewritten to use taint instead.

**Comment by LewisArdern** [comment]
https://semgrep.dev/orgs/LewisArdern/editor/s/LewisArdern:express-sequelize-injection

**Comment by 0xDC0DE** [comment]
I think Lewis’ rule looks good! Much better than the current one. I noticed that the original rule is in the `/lang` dir, but the id of the rule by Lewis is `express-…` 
The library used is sequelize and there is a directory for `sequelize` as well. It has a rule that looks related:

https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/sequelize/security/audit/sequelize-raw-query.yaml

I think I would: remove the rule in the `\lang` dir, use Lewis' rule to replace the rule in the `sequelize` dir.

**Comment by enncoded** [comment]
Update: Lewis' rule lives in [this branch](https://github.com/returntocorp/semgrep-rules/compare/leland-typescript-rules)
