### ISSUE TITLE
Semgrep stopped working with default "--config auto" flag

### ISSUE THREAD

**Issue by themenucha** [returntocorp/sgrep-rules#1994]
**Describe the bug**
Semgrep stopped working with default "--config auto" flag
 Looks like due to issue in one of the default rules:

`semgrep --config auto demo_test
Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate recommended rules based on
your languages and frameworks.
Fetching rules from https://semgrep.dev/registry ...
Failed to download config from https://semgrep.dev/c/auto: semgrep error: Invalid rule schema
  --> https://semgrep.dev/...:5196
5196 |   - patterns:
5197 |     - pattern: |
5198 |         $W(..., aws_secret_access_key="$ACCESSKEY", ...)
5199 |     - metavariable-regex:
5200 |         metavariable: $ACCESSKEY
5201 |         regex: ^[A-Za-z0-9/+=]+$
5202 |     - metavariable-analysis:
5203 |         metavariable: $ACCESSKEY
5204 |         analyzer: entropy
5205 |   - patterns:

Additional properties are not allowed ('metavariable-analysis' was unexpected)

invalid configuration file found (1 configs were invalid)`

**To Reproduce**
run: **semgrep --config auto [DIRECTORY]**

**Expected behavior**
Expected behavior is to work with default rule set

**Priority**
How important is this to you?
- P0: blocking me from making progress

**Desktop (please complete the following information):**
 - OS: RHEL 8
 - Browser NA
 - Version semgrep-0.81.0 (pip default)

**Comment by ievans** [comment]
Hi @themenucha — we’re working on making the language here clearer, but the fix is just to upgrade semgrep to 0.86.5 or higher. The engine added new syntax that is now in rules being served by the auto config!

feel free to re-open if upgrading doesn’t work
