### ISSUE TITLE
False positive for rule java.lang.security.audit.formatted-sql-string

### ISSUE THREAD

**Issue by dgian** [returntocorp/sgrep-rules#2024]
**Describe the bug**
`java.lang.security.audit.formatted-sql-string` rule is matched when using `execute` named in a method, outside of SQL context.

**To Reproduce**
https://semgrep.dev/s/0WKr

**Expected behavior**
Should not report `execute` as a match for SQL injection

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by colleend** [comment]
Should be fixed by the PR mentioned above! Feel free to let us know if there are more issues 😄

**Comment by dgian** [comment]
> Should be fixed by the PR mentioned above! Feel free to let us know if there are more issues smile

Many thanks @colleend . This was very quick! 👍🏽 
Do you have an idea of when is this going to be included in a registry release? Thanks again

**Comment by colleend** [comment]
Hi! It will most likely take until Monday or Tuesday for these changes to be reflected in the registry.
