### ISSUE TITLE
False positive with subprocess.run()

### ISSUE THREAD

**Issue by djmattyg007** [returntocorp/sgrep-rules#2078]
**Describe the bug**
The rule `python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use` has a few shortcomings:

- It doesn't understand passing tuples (as opposed to lists)
- It doesn't understand `sys.executable` as the first argument

It's also possible that it doesn't understand passing a non-user-controlled `Path` object (cast to a string) as the second value in the tuple supplied to `subprocess.run()`.

**To Reproduce**

```
import subprocess
from pathlib import Path

_CMD_PATH = Path(__file__).parent.parent / "plugin.py"

def run_script():
    # None of these values (except the environment variables) are user-controlled. This is fine.
    result = subprocess.run(
        (sys.executable, str(_CMD_PATH)),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=10,
        check=True,
    )
```

**Expected behavior**
There's no reason to warn in any capacity on the above code, because there are no user-controlled values being supplied. There is no reason to manually quote anything either, because python takes care of escaping everything properly for me.

**Priority**
How important is this to you?
- [x] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

While there's no ability to disable individual rules, and the need to turn on `--error` and `--strict` so that CI builds actually fail, any rule with a false positive is blocking.

**Additional Context**

**Comment by 0xDC0DE** [comment]
Hi @djmattyg007 ! 
Thanks for your bug report! 

The rule you are referencing here is an `audit` rule. In the README you will find some information about these rules:
> If a security rule is discouraging the use of a bad pattern (such as formatted SQL strings), we recommend appending audit to your namespace. This distinguishes it from a security rule that is specifically aiming to detect a vulnerability.

So, I understand that this is flagging code for you that is not vulnerable, but this is kind of the intention of this type of rule. Generally, there will be a tradeoff for rules. The more accurate they are (and hence the lower the false positive rate), the more likely they are also going to miss some cases (false negatives). The idea behind audit rules is that they can be used by security professionals to audit a repository, and easily find interesting parts in the code to inspect closer.

We are currently working on creating more accurate, vulnerability detecting rules. These rules will make use of our [taint mode](https://semgrep.dev/docs/writing-rules/data-flow/taint-mode/). For Python we have Django and Flask rules on our roadmap for this quarter.

I think it is unlikely that this rule will be updated. Instead, new rules and rulepacks will be created that better fit your expectation.

**Comment by enncoded** [comment]
Thanks for the feedback! You can track this change here https://github.com/returntocorp/semgrep-rules/pull/2558.
