### ISSUE TITLE
Some OWASP XXE rules can be improved

### ISSUE THREAD

**Issue by 0xDC0DE** [returntocorp/sgrep-rules#2111]
This rule:
contrib.owasp.java.xxe.documentbuilderfactory.owasp.java.xxe.javax.xml.parsers.DocumentBuilderFactory

is a lower quality version of
java.lang.security.audit.xxe.documentbuilderfactory-disallow-doctype-decl-false.documentbuilderfactory-disallow-doctype-decl-false
java.lang.security.audit.xxe.documentbuilderfactory-disallow-doctype-decl-missing.documentbuilderfactory-disallow-doctype-decl-missing

As pointed out in this PR:
https://github.com/returntocorp/semgrep-rules/pull/2064

**Comment by 0xDC0DE** [comment]
Oh. Looks like these rules are actually linked in the OWASP Cheatsheet series
https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#semgrep-rules

**Comment by 0xDC0DE** [comment]
Looks like there are a number of OWASP rules that can be improved. Should we consider updating rules and making a PR to the OWASP cheat sheet?

**Comment by 0xDC0DE** [comment]
OWASP rules say to set all three features:

- setFeature("[http://apache.org/xml/features/disallow-doctype-decl](http://apache.org/xml/features/disallow-doctype-decl)", true);
- setFeature("[http://xml.org/sax/features/external-general-entities](http://xml.org/sax/features/external-general-entities)", false);
- setFeature("[http://xml.org/sax/features/external-parameter-entities](http://xml.org/sax/features/external-parameter-entities)", false);

Problem: "[http://apache.org/xml/features/disallow-doctype-decl](http://apache.org/xml/features/disallow-doctype-decl)" alone is sufficient, other measures can be used as a backup

These rules are linked in OWASP Cheatsheet: [https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#semgrep-rules](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#semgrep-rules)

### List of incorrect/incomplete OWASP rules:

- contrib.owasp.java.xxe.digester3-digester.owasp.java.xxe.org.apache.commons.digester3.Digester
- contrib.owasp.java.xxe.documentbuilderfactory.owasp.java.xxe.javax.xml.parsers.DocumentBuilderFactory
    - Higher quality alternatives:
        - java.lang.security.audit.xxe.documentbuilderfactory-disallow-doctype-decl-false.documentbuilderfactory-disallow-doctype-decl-false
        - java.lang.security.audit.xxe.documentbuilderfactory-disallow-doctype-decl-missing.documentbuilderfactory-disallow-doctype-decl-missing
        - java.lang.security.audit.xxe.documentbuilderfactory-external-general-entities-true.documentbuilderfactory-external-general-entities-true
        - java.lang.security.audit.xxe.documentbuilderfactory-external-parameter-entities-true.documentbuilderfactory-external-parameter-entities-true
    - Duplicate of: gitlab.find_sec_bugs.XXE_XPATH-1.XXE_DOCUMENT-1
- contrib.owasp.java.xxe.saxbuilder.owasp.java.xxe.org.jdom2.input.SAXBuilder
- contrib.owasp.java.xxe.saxreader.owasp.java.xxe.org.dom4j.io.SAXReader
- contrib.owasp.java.xxe.xmlreader.owasp.java.xxe.org.xml.sax.XMLReader
    - Duplicate of: gitlab.find_sec_bugs.XXE_XMLREADER-1

**Comment by 0xDC0DE** [comment]
Issue tracked in linear: https://linear.app/r2c/issue/RULES-614/clean-up-java-xxe-rules-as-described-in-notion-page

**Comment by colleend** [comment]
thanks for creating the issue 😁

**Comment by inkz** [comment]
done!
