### ISSUE TITLE
Deliver clear list of validated checks

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep-rules#214]
Shippable file where all checks within that file are validated and are valuable to Django shops.

@minusworld: This could be a YAML file.

This will be the validated subset of the 18 checks in https://returntocorp.quip.com/w41oA2VbuVmP/Check-Checkpoints.

For all of these checks, we will attempt to hunt trophies and add discoveries to the trophy case at https://docs.google.com/spreadsheets/d/1ZZYrHh5CmV46wTY2h9t4dLeLuAeZDODqn_JWmYCsA10/edit#gid=0 .

**Comment by minusworld** [comment]
So far, these made the cut:

**Django**

- no-raw-sql
- use-count-instead-of-len
- no-null-true-on-text-field
- null-true-required-on-text-field
- use-jsonresponse
- open-redirect
- use-decimalfield-for-money

**Flask**

- no-routes-with-same-name

**Comment by minusworld** [comment]
Validated Django checks YAML file:
https://gist.githubusercontent.com/minusworld/467fe121adb46681c6d43524417df2b7/raw/9ec8d8e94f2fe0404c61c3af21be1277af8058fe/django-validated-rules-20200304.yml

**Comment by minusworld** [comment]
Platform job:
https://dev.massive.ret2.co/jobs/634?page=1&sort_on=repo_url&sort_by=asc

**Comment by minusworld** [comment]
Better platform job:
https://dev.massive.ret2.co/jobs/635?page=1&sort_on=repo_url&sort_by=asc

**Comment by minusworld** [comment]
-> Add these to r2c.registry.latest

**Comment by minusworld** [comment]
Done: https://rtc-web.s3-us-west-1.amazonaws.com/default-r2c-checks

**Comment by nbrahms** [comment]
LGTM 👍
