### ISSUE TITLE
JS Open redirect rule to support other types of strings

### ISSUE THREAD

**Issue by v1adko** [returntocorp/sgrep-rules#2149]
**Describe the bug**
I may be wrong, but it seems that the open redirect rule is missing other ways of ensuring a string is passed.

**To Reproduce**
```js
const url = "/string-path"
window.location.replace(url)
```

**Expected behavior**
In the rule definition it seems that only a directly hard coded string with double quotes `""` is allowed, however, there are more ways to ensure a string, like TypeScript or string literals, casting or .toString()

Is there any other way to make to rule happy while also allowing to define the paths elsewhere? (needed for our react component library)

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by LewisArdern** [comment]
Hey @v1adko would love to add something like this. Can you provide a playground link (https://semgrep.dev/playground) with a vulnerable example you would like us to cover? 

Personally, this would be fine:
```
const url = "/string-path"
window.location.replace(url)
```
since its hard-coded. We already are working on a rule which takes things like:
```
let value = new URLSearchParams($WINDOW.location.hash.substring(1))
let value = new URLSearchParams($WINDOW.location.search).get('return')

window.location.replace(value)

```

etc.

**Comment by v1adko** [comment]
Hey @LewisArdern. Thanks for such a fast response. Well the code I mentioned above is the simplest case, in my actual implementation it's a bit more complicated. We pass the string (still hardcoded) to a library component, so it look like this.

```jsx
<Menu entries={[{ label: 'One', route: '/one', }, { label: 'Two', route: '/two' }]} />
```

and then inside of menu we have an `onClick` handler
```js
() => window.location.replace(entry.route)
```

This is the rule in question - https://semgrep.dev/r?q=javascript.browser.security.open-redirect.js-open-redirect
Related code in the repo - https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/browser/security/open-redirect.js

Not sure if this is what you were asking (Playground), but hopefully it will be helpful - https://semgrep.dev/s/5e53

**Comment by LewisArdern** [comment]
Yes that is the playground! 

I created an internal ticket to add it to our support queue. We recently updated our JSX/TSX bindings for taint mode, which will be able to capture vulnerable instances of this from known sources.

We should have a rule out in the next week or so! Will reference this issue once the PR is in.

**Comment by LewisArdern** [comment]
Hey @v1adko what do you think of https://semgrep.dev/s/pAne as a starting rule?

Lewis

**Comment by v1adko** [comment]
@LewisArdern looking great and seems to work as expected!

**Comment by LewisArdern** [comment]
Cool, i will make a PR today or tomorrow to that rule so it should be better than what it was :)
