### ISSUE TITLE
Misleading semgrep autofix message for defusedxml

### ISSUE THREAD

**Issue by artemrys** [returntocorp/sgrep-rules#2153]
**Describe the bug**

We are using semgrep GitHub Action in one of the projects and it seems to be giving a misleading information about the autofix which is not working if you implement the autofix.

Here is the result of what semgrep prints.
```
  splunktaucclib/data_collection/ta_data_collector.py 
     splunk.use-defused-xml
        Found use of the native Python XML libraries, which is vulnerable to XML external entity
        (XXE) attacks. The Python documentation recommends the 'defusedxml' library instead. Use
        'defusedxml'. See https://github.com/tiran/defusedxml for more information.
        Details: https://sg.run/JekP
         ▶▶┆ Autofix ▶ s/xml/defusedxml/g
         21┆ import xml.sax.saxutils as xss
```
There is no `saxutils` under `defusedxml.sax` (https://github.com/tiran/defusedxml/blob/6c7a8ed9b7d3cf871ae5ff72e76e4d2e2297c74d/defusedxml/sax.py).

**To Reproduce**
Have the import mentioned above in your Python code.

**Expected behavior**
Provide better autofix message or remove existing one for this particular case.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Additional context**
The Github Actions run was on Ubuntu 20.04.4 LTS, semgrep 0.97.0 on python 3.10.5.

**Comment by enncoded** [comment]
Thanks for the feedback! I've gone ahead and removed the autofix from that rule, as we determined it has too many cases to handle with the current autofix.
