### ISSUE TITLE
 python.requests.best-practice.use-timeout autofix is overly aggressive

### ISSUE THREAD

**Issue by ryanking** [returntocorp/sgrep-rules#2155]
When [this rule](https://github.com/returntocorp/semgrep-rules/blob/399591555e8428c992966c74a53c8ef3191cff13/python/requests/best-practice/use-timeout.yaml#L46) is used with `--autofix` and nested function calls, the resulting fix is overly aggressive, adding the timeout parameter to all nested function calls.

This:

```python
requests.get(get_url())
```

becomes:

```python
requests.get(get_url(,timeout=30), timeout=30)
```

**Comment by enncoded** [comment]
What version of semgrep were you using? I just tested with 0.98 and the latest 0.101.1 and wasn't able to reproduce this behavior on both the CLI and the web playground.

**Comment by ryanking** [comment]
I am using 0.98.0

**Comment by ryanking** [comment]
It seems the key is having a newline in the function arguments.

Autofix handles this fine:

```python
requests.get(get_url())
```
but not this:

```python
requests.get(
  get_url()
)
```

Example diff on the latter:
```diff
diff --git a/main.py b/main.py
index af1187a..a469db3 100644
--- a/main.py
+++ b/main.py
@@ -1,3 +1,5 @@
 import requests
 
-requests.get(get_url())
+requests.get(
+    get_url(, timeout=30)
+, timeout=30)
```

**Comment by inkz** [comment]
the issue addressed here: https://github.com/returntocorp/semgrep-rules/pull/2213
