### ISSUE TITLE
javascript.lang.security.audit.non-constant-sql-query.non-constant-sql-query generates false positives

### ISSUE THREAD

**Issue by ianmuscat** [returntocorp/sgrep-rules#2166]
#### Describe the bug
The `javascript.lang.security.audit.non-constant-sql-query.non-constant-sql-query` rule incorrectly reports Sequalize queries that use `replacements` (as opposed to string concatenation) in SQL queries as vulnerable to SQL injection.

#### To Reproduce
```javascript
function bar (input) {
    models.sequelize.query(
        `SELECT * FROM bar WHERE bar LIKE '%:x%'`,
        {
          type: 'SELECT',
          replacements: {
            x: input
          }
        })
      .then(([bar]) => {
        console.log(bar);
      })
}
```

#### Expected behavior
This rule should not evaluate to true since this code is not vulnerable to SQL injection.

#### Priority
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

#### Additional Context
Adding `pattern-not: $DB.sequelize.query("...", {...})` to the rule seems to produce the correct result, however, there seems to have been some discussion about switching to a superior rule in https://github.com/returntocorp/semgrep-rules/issues/1980

**Comment by enncoded** [comment]
Thanks for the feedback! We'll be replacing this rule with the improved rule very soon, but for now I can add your change to this current rule.
