### ISSUE TITLE
Clarification on License for commercial use

### ISSUE THREAD

**Issue by zer00oo0-hu** [returntocorp/sgrep-rules#2173]
Hi Team, 

I went through the license https://github.com/returntocorp/semgrep-rules/blob/develop/LICENSE but i would like to get some clarification from a community member or r2c member.

Can someone use these rules and semgrep binary to integrate it into their SaaS application, for which users will be paying?

**Comment by enncoded** [comment]
Hi @InternGoUser, thanks for the question!

semgrep binary = yes, it’s LGPL
semgrep-rules are licensed under commons clause, so: no

https://semgrep.dev/docs/faq/#how-are-semgrep-and-its-rules-licensed

You can email [support@r2c.dev](mailto:support@r2c.dev) if you’re interested in using the rules commercially
