### ISSUE TITLE
Direct use of `HttpResponse` doesn't lead to XSS on non-HTML content type

### ISSUE THREAD

**Issue by Pamplemousse** [returntocorp/sgrep-rules#2196]
**Describe the bug**
The rule `python.django.security.audit.xss.direct-use-of-httpresponse.direct-use-of-httpresponse` gets triggered on `HttpResponse`, even if the specified `content_type` is not `text/html`.

**To Reproduce**
On this example code:

```python
# example.py
from django.http import HttpResponse

def endpoint():
    return HttpResponse(json.dumps({ 'status': 'ERROR', 'error': str(e) }), content_type='text/json')
```

`semgrep` reports the violation:

```bash
$ semgrep -c semgrep-rules/python/django/security/audit/xss/direct-use-of-httpresponse.yaml example.py 
Scanning 1 file.

Findings:

  example.py 
     direct-use-of-httpresponse
        Detected data rendered directly to the end user via 'HttpResponse' or a similar object. This
        bypasses Django's built-in cross-site scripting (XSS) defenses and could result in an XSS
        vulnerability. Use Django's template engine to safely render HTML.

          4┆ return HttpResponse(json.dumps({ 'status': 'ERROR', 'error': str(e) }), content_type='text/json')

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 1 rule on 1 file: 1 finding.
```

**Expected behavior**

I was expecting the rule not to flag this example.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by inkz** [comment]
Good catch. Thanks a lot! fix is available here: https://github.com/returntocorp/semgrep-rules/pull/2211
