### ISSUE TITLE
appservice-account-identity-registered.yaml may need tightening

### ISSUE THREAD

**Issue by kishorbhat** [returntocorp/sgrep-rules#2214]
**Describe the bug**
[This rule](https://github.com/returntocorp/semgrep-rules/blob/release/terraform/azure/security/appservice/appservice-account-identity-registered.yaml) fires in cases where the `identity` block is set but the identity type is not `UserAssigned`. It is valid to have an identity block with `type` set to `SystemAssigned` ([Terraform docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#identity)), where Azure generates the service principal for you. In this case, the `identity_ids` attribute is not required.

**To Reproduce**
Run https://sg.run/PbXY on https://github.com/seattle-uat/civiform/blob/main/cloud/azure/modules/app/main.tf#L91-L139.

**Expected behavior**
No warning since an identity block is set.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Comment by inkz** [comment]
Thanks a lot, the issue addressed in this PR: https://github.com/returntocorp/semgrep-rules/pull/2215

**Comment by kishorbhat** [comment]
Great, thanks!
