### ISSUE TITLE
insecure-load-balancer-tls-version.yaml needs to be more permissive

### ISSUE THREAD

**Issue by kishorbhat** [returntocorp/sgrep-rules#2217]
**Describe the bug**
[insecure-load-balancer-tls-version](https://github.com/returntocorp/semgrep-rules/blob/release/terraform/aws/security/insecure-load-balancer-tls-version.yaml) checks that the ELB SSL policy is set to `ELBSecurityPolicy-FS-1-2-Res-2019-08` and fires if not. However, per [AWS documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html#describe-ssl-policies), there are three SSL policies that can be used for TLS 1.2:
- ELBSecurityPolicy-FS-1-2-Res-2020-10
- ELBSecurityPolicy-FS-1-2-Res-2019-08 
- ELBSecurityPolicy-FS-1-2-2019-08

All of them allow only TLS 1.2, but differ in the ciphers they support. The "FS security policies" table further down the page is helpful to compare the three.

**To Reproduce**
Run https://sg.run/187G against [insecure-load-balancer-tls-version.tf](https://github.com/returntocorp/semgrep-rules/blob/release/terraform/aws/security/insecure-load-balancer-tls-version.tf) after changing any of the `ssl_policy` lines to `ELBSecurityPolicy-FS-1-2-Res-2020-10`.

**Expected behavior**
No warning/alert since it's a valid TLS1.2-only SSL policy.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Comment by inkz** [comment]
thanks, going to be fixed by: https://github.com/returntocorp/semgrep-rules/pull/2228
