### ISSUE TITLE
generic.secrets.security.detected-username-and-password-in-uri.detected-username-and-password- detects items in package-lock.json

### ISSUE THREAD

**Issue by raoganeshr** [returntocorp/sgrep-rules#2218]
**Describe the bug**
generic.secrets.security.detected-username-and-password-in-uri.detected-username-and-password- falsely detects items in npm package-lock.json.

**To Reproduce**
Run the rule on a package-lock.json created by npm. For some entries, it triggers an error.

example entry:

 "resolved": "https://someurl.com/repository/api/npm/npm/@companyname/package/-/@companyname/package-0.0.26.tgz",
 "integrity": "sha1-j7OrmTVAlcCLPwnpcN603XKHP4Q=",
 "dependencies": {
   "moment": "^2.29.3",
   "tslib": "^2.3.0"
 },
 "peerDependencies": {
 "@angular/cdk": "^12.2.9",

**Expected behavior**
The rule should be fixed to prevent this match.

**Priority**
How important is this to you?
P2: Since we excluded package-lock.json from the semgrep scan.

**Screenshots**

**Desktop (please complete the following information):**
Version: latest

**Comment by inkz** [comment]
thanks a lot! fixed by: https://github.com/returntocorp/semgrep-rules/pull/2222
