### ISSUE TITLE
Failed to download config from https://semgrep.dev/p/typescript: semgrep error: Invalid rule schema

### ISSUE THREAD

**Issue by elishagreenwald** [returntocorp/sgrep-rules#2243]
**Describe the bug**

Just started getting "Failed to download config from https://semgrep.dev/p/typescript: semgrep error: Invalid rule schema" wondering if it's related to recent commits. If not, ignore me and sorry! Can provide more details if necessary but wanted to open this ASAP.

`Fetching rules from https://semgrep.dev/registry ...
Failed to download config from https://semgrep.dev/p/typescript: semgrep error: Invalid rule schema
  --> https://semgrep.dev/...:1343`

**To Reproduce**

**Expected behavior**

**Priority**
How important is this to you?
- [x ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kurt-r2c** [comment]
@elishagreenwald what version of the CLI are you running?

**Comment by elishagreenwald** [comment]
> @elishagreenwald what version of the CLI are you running?
returntocorp/semgrep:0.83.0 🙃

**Comment by kurt-r2c** [comment]
Your CLI is quite old (21 releases behind). We would recommend updating to latest (0.104.0) if possible. Due to feature velocity, support for versions beyond a month or so is tenuous at best.

Do you have a version pinning requirement for CI?

**Comment by elishagreenwald** [comment]
> Your CLI is quite old (21 releases behind). We would recommend updating to latest (0.104.0) if possible. Due to feature velocity, support for versions beyond a month or so is tenuous at best.

Yeah that's fair! Let me try that!

**Comment by elishagreenwald** [comment]
That fixed it. Appreciate your help and sorry for the bother! Thanks!

**Comment by kurt-r2c** [comment]
thanks! Officially, we only support latest CLI for end users - if you are experiencing issues with a ruleset, it is likely your binary is out of date.
