### ISSUE TITLE
False positive rule formatted-sql-string | SQL_INJECTION |

### ISSUE THREAD

**Issue by nitesh-sharma-01** [returntocorp/sgrep-rules#2281]
**Describe the bug**
`java.lang.security.audit.formatted-sql-string` rule is matched when using executeQuery / EntityManager.executeNativeQuery in a method

**To Reproduce**
[[Sample code to reproduce this behavior.](https://semgrep.dev/playground/r/java.lang.security.audit.formatted-sql-string.formatted-sql-string)](https://semgrep.dev/s/RlNN)

**Expected behavior**
Should not report SQL_INJECTION for criteria query.
Should not report SQL_INJECTION if we are defining SQL query as a constant or pass dynamic query from derived method.
should not report SQL_INJECTION if we use setParameter() as suggested.

**Priority**
How important is this to you?
- [x] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by colleend** [comment]
Hi, thanks for filing this issue! Unfortunately, open-source Semgrep currently doesn't support true interprocedural constant propagation (which is needed to determine that the input to `dynamicQuery` is a constant and therefore the `jql` is a constant string). If you want to have Semgrep with more functionality included, there is https://semgrep.dev/deep-semgrep-beta/ that you can try. DeepSemgrep will have better support for interprocedural taint (which this case utilizes), too. 

Thanks for your submission -- this is a great example! Unfortunately, open-source Semgrep doesn't have the features to catch this. Feel free to fill out the form if you want to check out DeepSemgrep!
