### ISSUE TITLE
False positives with subprocess funcs in Python

### ISSUE THREAD

**Issue by vx-sec** [returntocorp/sgrep-rules#2554]
**Describe the bug**
Python rules concerning dangerous subprocess calls all lack the check for when the arguments to subprocess.$FUNCs are given in tuples and not lists, which results in false positives in rulesets not in taint mode, f.e [this](https://semgrep.dev/playground/r/python.lang.security.audit.dangerous-subprocess-use-audit.dangerous-subprocess-use-audit) audit rule. While i understand that audit rules are meant to be noisy, i dont think this addition will increase the number of false negatives, but will definitely decrease the number of false positives. From what I understand its a matter of adding one pattern-not with a tuple as an argument to a subprocess.$FUNC(). 

**To Reproduce**
`subprocess.call(("echo", "a", ";", "rm", "-rf", "/"))`

**Expected behavior**
checking for subprocess.call((....)) should not yield any different results than subprocess.call([...]).
In the above example 

**Priority**
How important is this to you?
- [x] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Additional Context**
https://github.com/returntocorp/semgrep-rules/issues/2078

**Comment by enncoded** [comment]
Thanks for the feedback! You can track this change here https://github.com/returntocorp/semgrep-rules/pull/2558.

**Comment by vx-sec** [comment]
Thanks for taking up the issue. The fix you provided is precisely what I had in mind. However it is not only the audit rule that lacks the tuple matching. All python security rules that check for  subprocess calls lack the check for tuples. I think adding the tuple checks for them would help with false positives too in some edge cases as they are taint rules.
Examples: 
- https://semgrep.dev/playground/r/python.lang.security.dangerous-subprocess-use.dangerous-subprocess-use
- https://semgrep.dev/playground/r/python.lang.security.audit.dangerous-subprocess-use-tainted-env-args.dangerous-subprocess-use-tainted-env-args

**Comment by enncoded** [comment]
Oh I see. Yeah, I can add those right now. Good catch!

**Comment by enncoded** [comment]
Closing this, feel free to reopen and ping me if you see anymore issues. Thanks so much!
