### ISSUE TITLE
javascript.express.security.audit.xss.mustache.explicit-unescape.template-explicit-unescape false positives

### ISSUE THREAD

**Issue by nightshiba** [returntocorp/sgrep-rules#2555]
**Describe the bug**
`javascript.express.security.audit.xss.mustache.explicit-unescape.template-explicit-unescape` generates false positives for `&` inside the strings

**To Reproduce**
[Sample code to reproduce this behavior.](https://semgrep.dev/s/GL3n) (line #50)

**Expected behavior**
The rule should not be triggered for `&` inside the strings

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Comment by 0xDC0DE** [comment]
Hi @nightshiba, thanks for the report! I've made some updates to the rule. The issue will be fixed when this work gets released.

**Comment by nightshiba** [comment]
> Hi @nightshiba, thanks for the report! I've made some updates to the rule. The issue will be fixed when this work gets released.

Hello @0xDC0DE, thanks for the fix, but it seems that the mentioned PR was closed by the bot..

**Comment by LewisArdern** [comment]
Looks like it was merged, closing ticket. Please reopen if your issue is not resolved!
