### ISSUE TITLE
Fix FPs for Java XXE rules

### ISSUE THREAD

**Issue by inkz** [returntocorp/sgrep-rules#2572]
from user:

> Hi, I'm trying to resolve the issue, "CWE-611: Improper Restriction of XML External Entity Reference" with my Java code. I have added the line,  documentBuilderFactory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true); as mentioned in the suggestion to overcome the issue. But still it gives High severity on the same line.
Then I checked on the [Semgrep.dev](http://semgrep.dev/) editor. Seems like if the variable is declared in the classscope, Semgrep cannot detect it

**Comment by 0xDC0DE** [comment]
I think this should be addressed in the recent changes I already made.
