### ISSUE TITLE
False positives on php.lang.security.audit.assert-use-audit.assert-use-audit

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#2623]
[semgrep-rules/assert-use-audit.yaml at develop · returntocorp/semgrep-rules · GitHub](https://github.com/returntocorp/semgrep-rules/blob/develop/php/lang/security/audit/assert-use-audit.yaml)

```
     php.lang.security.audit.assert-use-audit.assert-use-audit
        Calling assert with user input is equivalent to eval'ing.
        Details: https://sg.run/39eb

         123┆ assert($log instanceof Logger);
```

I feel like semgrep can determine that this `instanceof` expression does not execute any user input.

**Comment by 0xDC0DE** [comment]
Hi Sjord! This could be possible with Semgrep, for this we usually use taint mode rules. Doing this has a tradeoff, we will usually have more accurate findings, and less false positives, but we also are likely to miss some cases and introduce false negatives.

This rule is part of the audit rules. These rules are created with security auditors in mind. They are intended to be used to mark locations in the code that an auditor might want to inspect more closely manually and are hence more prone to false positives. 

There is an equivalent vulnerability-finding rule as well, does this one meet your needs?
https://github.com/returntocorp/semgrep-rules/blob/develop/php/lang/security/assert-use.yaml

**Comment by Sjord** [comment]
Thanks @0xDC0DE. I didn't know there was also a taint mode rule for assert.

I am a security auditor and I generally appreciate when semgrep points out dangerous constructs, even if semgrep is not sure whether they are vulnerable. However, even with that in mind I think that this rule is matching too much. How do you think about excluding certain common boolean expressions in this rule? E.g.

```
- pattern-not: assert($A == $B, ...);
- pattern-not: assert($A instanceof $B, ...);
```

Can this be done in a smarter way than enumerating all boolean operators?

**Comment by Sjord** [comment]
Also, since PHP 8 it is no longer possible to pass a string to [`assert`](https://www.php.net/assert):

> Using string as the assertion is DEPRECATED as of PHP 7.2.0 and REMOVED as of PHP 8.0.0.

So maybe detecting assertions is not so important anymore.
