### ISSUE TITLE
No-opener is implicit on target=_blank, so semgrep rule is not needed

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#2625]
html.security.missing-noopener.missing-noopener warns about links opening in new tabs:

```
<a href="https://www.example.org" target="_blank">foo</a>
```

```
  a.html
     html.security.missing-noopener.missing-noopener
        This anchor tag with 'target="_blank"' is missing 'noopener'. A page opened with
        'target="_blank"' can access the window object of the origin page. This means it can
        manipulate the 'window.opener' property, which could redirect the origin page to a malicious
        URL. This is called reverse tabnabbing. To prevent this, include 'rel=noopener' on this tag
        Details: https://sg.run/5Q03

          1┆ <a href="https://www.example.org" target="_blank">foo</a>
```

However, rel=noopener is [no longer needed](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener) with modern browsers:

> **Note:** Setting `target="_blank"` on `<a>` elements now implicitly provides the same `rel` behavior as setting `rel="noopener"` which does not set `window.opener`. See [browser compatibility](/en-US/docs/Web/HTML/Element/a#browser_compatibility) for support status.

**Comment by LewisArdern** [comment]
@Sjord we deprecated this rule, is it still a problem for you? Re open if it is!

**Comment by Sjord** [comment]
I can still reproduce it:

```
$ semgrep -c 'r/html.security.missing-noopener.missing-noopener' index.html
Semgrep rule registry URL is https://semgrep.dev/registry.
Scanning 1 file.

Findings:

  index.html
     html.security.missing-noopener.missing-noopener
        This anchor tag with 'target="_blank"' is missing 'noopener'. A page opened with
        'target="_blank"' can access the window object of the origin page. This means it can
        manipulate the 'window.opener' property, which could redirect the origin page to a malicious
        URL. This is called reverse tabnabbing. To prevent this, include 'rel=noopener' on this tag
        Details: https://sg.run/5Q03

          1┆ <a href="https://www.example.org" target="_blank">foo</a>


Ran 1 rule on 1 file: 1 finding.
```

However, [the rule in semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/html/security/missing-noopener-or-noreferrer.yaml) has been changed to never match. Why? Why wasn't it simply deleted? Why isn't this changed rule used when I use rule 'r/html.security.missing-noopener.missing-noopener'?

**Comment by Sjord** [comment]
> Re open if it is!

I don't have the privileges to re-open this issue, apparently.

**Comment by LewisArdern** [comment]
I'll investigate, I deprecated this rule back in 2022, looks like a naming issue. 

https://github.com/returntocorp/semgrep-rules/blob/develop/html/security/missing-noopener-or-noreferrer.yaml

**Comment by Sjord** [comment]
I can still reproduce the problem. Please reopen.

**Comment by LewisArdern** [comment]
The registry hasn't been updated yet @Sjord it will be deprecated when we merge develop to release with this PR which includes the deprecation https://github.com/returntocorp/semgrep-rules/pull/2657 things merged into develop do not update the registry

**Comment by Sjord** [comment]
Thanks, this is solved now.
