### ISSUE TITLE
[Check] User data into Raw SQL and raw and extra

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#263]
**Description**
Check for user data coming from `request.$ANYTHING` into Raw SQL or .raw() or extra()
These are expansions of https://github.com/returntocorp/sgrep-rules/blob/develop/python/django/security/raw_query.yaml and https://github.com/returntocorp/sgrep-rules/blob/develop/python/django/db/query/query_set_extra.yaml.

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by ulziibay** [comment]
Jobs: https://dev.massive.ret2.co/jobs/748?page=1&sort_on=repo_url&sort_by=asc, https://dev.massive.ret2.co/jobs/749?page=1&sort_on=repo_url&sort_by=asc

**Comment by ulziibay** [comment]
job for extra: https://dev.massive.ret2.co/jobs/759?page=1&sort_on=repo_url&sort_by=asc
