### ISSUE TITLE
Error: Files in /stats/ folders missing keys

### ISSUE THREAD

**Issue by Salcybercat** [returntocorp/sgrep-rules#2636]
**Describe the bug**
Running semgrep with --config=~/semgrep-rules produces this error:

```
semgrep error: missing keys
  --> ~/semgrep-rules/stats/web_frameworks.yml:1
1 | python:
2 |   - flask
3 |   - django
4 | ruby:
5 |   - rails
6 | golang:
 
~/semgrep-rules/stats/web_frameworks.yml_0 is missing `rules` as top-level key
 
semgrep error: missing keys
  --> ~/semgrep-rules/stats/metacategory_to_support_tier.yml:1
1 | tier1:
2 |   - CSRF
3 |   - XSS
4 |   - "SQL Injection"
5 |   - "Command Injection"
6 |   - "Code Injection"
 
~/semgrep-rules/stats/metacategory_to_support_tier.yml_0 is missing `rules` as top-level key
 
semgrep error: missing keys
  --> ~/semgrep-rules/stats/cwe_to_metacategory.yml:1
1 | Cryptography:
2 |   - "CWE-523: Unprotected Transport of Credentials"
3 |   - "CWE-319: Cleartext Transmission of Sensitive Information"
4 |   - "CWE-326: Inadequate Encryption Strength"
5 |   - "CWE-327: Use of a Broken or Risky Cryptographic Algorithm"
6 |   - "CWE-329: Not Using a Random IV with CBC Mode"
 
~/semgrep-rules/stats/cwe_to_metacategory.yml_0 is missing `rules` as top-level key
 
[ERROR] invalid configuration file found (3 configs were invalid)
```
**_Cause of Issue:_**
These 3 .yaml files in the /stats/ folder are missing the line 'rules' as per template.yaml :
semgrep-rules/stats/web_frameworks.yml
semgrep-rules/stats/metacategory_to_support_tier.yml
semgrep-rules/stats/cwe_to_metacategory.yml

**_Workaround:_**
Remove the /stats/ folder from /semgrep-rules/

**To Reproduce**
1. Download semgrep version 1.2.1
2. Download semgrep-rules, branch: develop (default)
3. Run the following command in Terminal :
`semgrep --config=~/semgrep-rules -o semgrep_output /path/to/target/repo`

**Expected behavior**
Semgrep scan to run without any Error messages

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.6.1

**Comment by LewisArdern** [comment]
@Salcybercat You'll have to delete that folder if you directly want to run all rules from semgrep-rules. In general we recommend you run `--config=auto` or rulepacks like `p/default` e.g. https://semgrep.dev/p/default.

We do not recommend you run semgrep-rules, however this is not a semgrep-rules issues its an issue with the semgrep engine since we have no control over how it interprets things. Raise an issue over at https://github.com/returntocorp/semgrep if the above solutions do not work for you
