### ISSUE TITLE
Misleading AWS rules for encryption

### ISSUE THREAD

**Issue by adanalvarez** [returntocorp/sgrep-rules#2640]
**Describe the bug**
The following rules from terraform.aws.security:
- aws-cloudwatch-log-group-unencrypted
- aws-dynamodb-table-unencrypted
- aws-lambda-environment-unencrypted
- aws-secretsmanager-secret-unencrypted

Imply that the service has no encryption, but according to AWS documentation, these services have encryption by default.

**Expected behavior**
A message that mentions that AWS default encryption is used, but we still need to configure our custom KMS keys.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Additional context**
- aws-cloudwatch-log-group-unencrypted: "Log group data is always encrypted in CloudWatch Logs. By default, CloudWatch Logs uses server-side encryption for the log data at rest." https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html

- aws-dynamodb-table-unencrypted: "All user data stored in Amazon DynamoDB is fully encrypted at rest. DynamoDB encryption at rest provides enhanced security by encrypting all your data at rest using encryption keys stored in [AWS Key Management Service (AWS KMS)](https://aws.amazon.com/kms/)". https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EncryptionAtRest.html

- aws-lambda-environment-unencrypted: "Lambda always provides server-side encryption at rest with an AWS KMS key. By default, Lambda uses an AWS managed key. If this default behavior suits your workflow, you don't need to set anything else up." https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html

- aws-secretsmanager-secret-unencrypted: "Secrets Manager uses encryption via AWS Key Management Service (AWS KMS) to protect the confidentiality of data at rest. AWS KMS provides a key storage and encryption service used by many AWS services. Every secret in Secrets Manager is encrypted with a unique data key. Each data key is protected by a KMS key. You can choose to use default encryption with the Secrets Manager AWS managed key for the account, or you can create your own customer managed key in AWS KMS." https://docs.aws.amazon.com/secretsmanager/latest/userguide/data-protection.html

**Comment by inkz** [comment]
@adanalvarez thank you! we updated the messages :pray:
