### ISSUE TITLE
[Check] User data into os.path.join

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#269]
**Description**
Based on triaging of https://github.com/returntocorp/enterprise/issues/20 results, user data flowing into `os.path.join` is rarely good, being subject to path traversal attacks.

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by ulziibay** [comment]
Unfortunately nothing is found on the corpus:
https://dev.massive.ret2.co/jobs/802?page=1&sort_on=repo_url&sort_by=asc

https://dev.massive.ret2.co/jobs/801?page=1&sort_on=repo_url&sort_by=asc
