### ISSUE TITLE
Rule dockerfile.security.missing-user.missing-user always failed

### ISSUE THREAD

**Issue by mathieu-amblard** [returntocorp/sgrep-rules#2735]
**Describe the bug**
Even if a non root user is specified in the Dockerfile, the rule `dockerfile.security.missing-user.missing-user` failed

**To Reproduce**

- Go to https://semgrep.dev/playground/r/dockerfile.security.missing-user.missing-user?editorMode=advanced
- Uncomment `USER notroot`
- The two lines `CMD semgrep -f p/xss` and `CMD semgrep --config localfile targets` are still matching

**Expected behavior**
I expect the two lines pass.

**What is the priority of the bug to you?**

- P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- P2: regular bug that should get fixed

Thank you in advance for your help

**Comment by ievans** [comment]
thanks @mathieu-amblard - I transferred this issue to semgrep-rules repository as it appears to be an issue with the rule rather than the engine

**Comment by 0xDC0DE** [comment]
Hi @mathieu-amblard ! Thanks for your report!

Looks like during updates I made to this rule to add an autofix I dropped a `pattern-inside`. Because there is no secure testcase possible without changing the testfile this slipped through the automated tests and the review. I fixed it!

**Comment by mathieu-amblard** [comment]
Hi @0xDC0DE ,
Thank you for your reactivity and the fix 👍 !
