### ISSUE TITLE
Add exclusions to rule `generic.secrets.security.detected-aws-account-id.detected-aws-account-id`

### ISSUE THREAD

**Issue by gdavison** [returntocorp/sgrep-rules#2750]
**Is your feature request related to a problem? Please describe.**

The rule `generic.secrets.security.detected-aws-account-id.detected-aws-account-id` matches any 12-digit number preceded by some varation of "AWS Account ID". We include these values in documentation and acceptance tests, and would prefer to not have to annotate each occurrence.

**Describe the solution you'd like**

Defining one or more "example" account IDs, such as `123456789012` that will be ignored.

For example, the rule [`generic.secrets.security.detected-aws-secret-access-key.detected-aws-secret-access-key`](https://github.com/returntocorp/semgrep-rules/blob/develop/generic/secrets/security/detected-aws-secret-access-key.yaml) ignores secret access keys that include `example`, among others.

**Comment by LewisArdern** [comment]
Hey @gdavison I hear you and agree we should be doing that.

I made a PR, let me know if it meets your expectations or you want other numbers to be included!
