### ISSUE TITLE
[Check] SSRF, where user data goes into an http request

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#278]
**Description**
Check for user data going into an http request (`request` library or `urllib` library), which is SSRF.

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by nbrahms** [comment]
OWASP SSRF: https://owasp.org/www-community/attacks/Server_Side_Request_Forgery

**Comment by nbrahms** [comment]
A reasonable implementation is blocked on https://github.com/returntocorp/sgrep/issues/353

**Comment by nbrahms** [comment]
Unblocked with the magic of Jinja templating: https://github.com/returntocorp/sgrep-rules/pull/290

**Comment by nbrahms** [comment]
No findings on any repositories, so skipping triage labelling 😞
