### ISSUE TITLE
How to update a contribution PR through playground ?

### ISSUE THREAD

**Issue by Gby56** [returntocorp/sgrep-rules#2798]
**Describe the bug**
I've tried to contribute via the cool playground PR creator, but sadly I had linting errors on the PR that the bot created. (I wonder if the in-browser linter could at least detect missing rule tags/metadata ?)

<img width="486" alt="image" src="https://user-images.githubusercontent.com/6706472/225266859-f29c3a74-d0ba-4e98-a53f-3d453f2c4a69.png">

So I'm kinda stuck, I can't fix my rule I think, unless I rename it and make another PR
Or maybe I can do an old-school fork PR otherwise

**To Reproduce**
Simply make a faulty rule that is missing a technology field in the metadata and contribute via playground

**Expected behavior**
The backend processing should figure out the existing PR and just push another commit ?
Or maybe it should do that in the background, checking if a user has saved a new version of the rule on the Playground ?

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [X] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by enncoded** [comment]
Hi @Gby56, this is the wrong repo for this kind of bug, as it's a bug in the Semgrep App. I've forwarded this (and the ~3 other bugs that you ran into, sorry about that 😄) to our app team so they can take care of it. I'll close this issue in the meantime. Thanks for filing this nonetheless though, makes writing up the support ticket easier :)
