### ISSUE TITLE
[Check] Check for user data in formatted filenames

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#282]
**Description**
Look for a pattern like this: `'hours_{0}_to_{1}_by_{2}.csv'.format($V)`. Inspired by https://dev.massive.ret2.co/triager/triage/753/70547?sort_by=path&asc=1&selected_regions=%5B%7B%22cols%22%3A%5B3%2C3%5D%2C%22rows%22%3A%5B1%2C1%5D%7D%5D

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by ulziibay** [comment]
@minusworld: enumerating through all the possible file extensions seems quite cumbersome at the moment! Honestly, just the data flow into something like "'hours_{0}_to_{1}_by_{2}.csv'.format($V)" is not a necessary indication of bad behavior. My vote on this check is to no-op.

I will prioritize https://github.com/returntocorp/sgrep-rules/issues/269 over this.

**Comment by ulziibay** [comment]
@

**Comment by ulziibay** [comment]
job: https://dev.massive.ret2.co/jobs/826?page=1&sort_on=repo_url&sort_by=asc

**Comment by ulziibay** [comment]
Another job: https://dev.massive.ret2.co/jobs/833?page=1&sort_on=repo_url&sort_by=asc

**Comment by ulziibay** [comment]
@minusworld there is something wrong on platform: https://dev.massive.ret2.co/jobs/833?page=1&sort_on=repo_url&sort_by=asc should show the findings for the examples linked in the ticket!

**Comment by minusworld** [comment]
Yeah, I'm discovering that as well. I'm having the same problem with the email check. I'm going to make a new ticket for debugging this.

**Comment by minusworld** [comment]
https://github.com/returntocorp/echelon-backend/issues/4109

**Comment by minusworld** [comment]
Closing this issue because the check is written, but there is an issue to debug in the above ticket. Tracking that work in the above ticket.
