### ISSUE TITLE
False positive for model-attributes-attr-accessible on Ruby when compared to Brakeman 

### ISSUE THREAD

**Issue by nightpool** [returntocorp/sgrep-rules#2913]
**Describe the bug**

When scanning Ruby code, any class in the entire codebase is checked for the presence of the `attr_accessible` macro, even utility classes or small helper classes that have nothing to do with ActiveRecord and are unlikely to have functions that would allow mass-assignment. In contrast, the Brakeman check that this rule is based on explicitly only applies it for classes that descend from ActiveRecord::Base

https://github.com/presidentbeef/brakeman/blob/38306e24507cc74f07a96bcdfe6769ec117bd524/lib/brakeman/checks/check_model_attributes.rb#L51

https://github.com/presidentbeef/brakeman/blob/38306e24507cc74f07a96bcdfe6769ec117bd524/lib/brakeman/tracker/model.rb#L25-L27

Because `model-attributes-attr-accessible` only represents a security risk when the model provides a method like `update_attributes`, `new`, or `update!` that accepts a hash of attribute names, and those methods in standard rails codebases are provided almost exclusively by ActiveRecord::Base, this restriction should be applied to the Semgrep rule as well. 

**To Reproduce**

```ruby
class TestObject < Struct.new(:name); end
TestObject.new("name")
```

This code matches the rule. It should not match the rule.

**Expected behavior**

The code above does not match the rule

**Priority**
How important is this to you?
- [x] P1: this will block me in the near future

**Additional Context**

The high rate of false positives for this vulnerability makes it very difficult to triage, because I have to manually inspect each file to determine whether the class inherits from ActiveRecord::Base or not.

**Comment by 0xDC0DE** [comment]
Hi @nightpool ,

As far as I am aware with Semgrep we can not currently check inheritance like that to reduce the amount of false positives. However, we've had this being asked a few times before and it might be on the roadmap soon. 

In the meantime I have checked the metadata of the rule and it being a `audit` type rule with `confidence: LOW` correctly reflects the "noisy" nature of this rule in its current state. I have also added your code example as a `todook` test syntax marking.

**Comment by IagoAbal** [comment]
> As far as I am aware with Semgrep we can not currently check inheritance

Semgrep Pro ~can~ should be able to do that (in the supported languages).

**Comment by 0xDC0DE** [comment]
I think this means that we won't be updating the rule for the open source version.

**Comment by nightpool** [comment]
@0xDC0DE Circling back on this—do you know what the status is for Semgrep Pro rules for Rails?
