### ISSUE TITLE
ActiveRecord SQL injection false positive when using `slice`

### ISSUE THREAD

**Issue by nightpool** [returntocorp/sgrep-rules#2914]
**Describe the bug**

Currently, semgrep-rules flags ActiveRecord code like `User.where(params[:query])` (which allows for a partial SQL string to be inserted) but allows code like `User.where(user_id: params[:user_id])` (where ActiveRecord will properly parameterize the query). However, it also falsely flags cases where a `where` hash is used (and the query is parameterized), but that hash is constructed using `slice` instead of using a hash literal. See below:

**To Reproduce**

```ruby
  def ok_test6
    user = User.where(user_id: params[:user_id])[0]
    user = User.where(params.slice(:user_id))[0]
  end
```

Although the two lines are identical, the second line is flagged by semgrep and the first line is not.

**Expected behavior**

Neither line is flagged.

**Priority**
How important is this to you?
- [x] P2: annoying but not blocking me

**Additional Context**

This resulted in only a small number of false-positives in our codebase, and although any false-positive is annoying, and this one was particularly scary since the code *looks* dangerous on first glance, it was relatively easy to resolve.

**Comment by 0xDC0DE** [comment]
Thanks @nightpool for reporting this false positive! The update for the rule will be merged soon.

**Comment by LewisArdern** [comment]
Looks like this should be fixed with the recent merge
