### ISSUE TITLE
false positive for - detected artifactory password rule

### ISSUE THREAD

**Issue by shsingh** [returntocorp/sgrep-rules#2949]
The rule is triggering based on its regex for the following code. https://github.com/apcj-f5/nap-devsecops-demo/blame/b4e09fed6041423a0d243aae8c06aac18d0a5118/argocd/manifests/hapi/nap-dos-logconf.yaml#L2

I am not an artifactory user so have no way of testing if the regex that picks up the false positive above can not be modified.

The file above is a standard Kubernetes definition for an NGINX product. It's based off a Kubernetes CRD declaration. Another false positive example at: https://github.com/apcj-f5/nap-devsecops-demo/blame/b4e09fed6041423a0d243aae8c06aac18d0a5118/argocd/manifests/hapi/nap-dos-policy.yaml#L2

--
This is currently low priority as it is not causing any issues in my workflow. Just wanted to see if there was a way to change the regex to catch the ARtifactory password without detecting issues with my Kubernetes manifests.

**Comment by kurt-r2c** [comment]
@shsingh is referring to this rule: https://github.com/returntocorp/semgrep-rules/blob/f211cca24d04ba5690b2ed655247a2530b19177e/generic/secrets/security/detected-artifactory-password.yaml
