### ISSUE TITLE
Confirming licensing for rules.

### ISSUE THREAD

**Issue by ajohnston9** [returntocorp/sgrep-rules#2954]
Hello, 

I'm a bit confused about the licensing of the rules within this repository. 

The LICENSE file lists both Commons Clause and LGPL 2.1, however this comment suggests Semgrep rules are licensed under the MIT License or a Semgrep-specific license:

https://github.com/returntocorp/semgrep-rules/issues/1245#issuecomment-1219504524

Can you clarify which license applies? Thanks in advance!

**Comment by LewisArdern** [comment]
@ajohnston9  It's mostly referenced here https://semgrep.dev/docs/licensing/#semgrep-registry-license

[Semgrep-Rules](https://github.com/returntocorp/semgrep-rules/blob/develop/LICENSE) is under [Common Clause](https://commonsclause.com/) with LGPL 2.1.

[Semgrep](https://github.com/returntocorp/semgrep) the CLI is LGPL 2.1 only.

Our [Pro rules](https://semgrep.dev/docs/semgrep-code/pro-rules/) which are not in this repository are licensed under a different Semgrep specific license. 

**None** of our licenses leverage MIT today, that information was considered in the other thread, but the licenses are as mentioned above.

cc @ievans if I answered any of this incorrectly.

**Comment by LewisArdern** [comment]
Closing this issue as no response, feel free to reach out if you have additional questions
