### ISSUE TITLE
License confusion with Rules

### ISSUE THREAD

**Issue by zer00oo0-hu** [returntocorp/sgrep-rules#3033]
Hi r2c team,

I was looking at your rules license and policy. As per your mentioned point "Semgrep Registry rules written by the Semgrep team are licensed under the [Commons Clause](https://github.com/returntocorp/semgrep-rules/blob/develop/LICENSE). The source for these Registry rules is available at [returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/). Those rules licensed under the Commons Clause license cannot be resold without Semgrep, Inc. (“Semgrep”)’s permission"

I was looking at this rule  - https://github.com/returntocorp/semgrep-rules/blob/release/yaml/semgrep/consistency/lang-consistency-bash.yaml

Here, you didn't mention license anywhere in this .yaml file but if we look at same rule at https://semgrep.dev/playground/r/yaml.semgrep.consistency.lang-consistency-bash.lang-consistency-bash?editorMode=advanced, i can see 
<img width="577" alt="image" src="https://github.com/returntocorp/semgrep-rules/assets/85396549/098b2561-e623-4798-8923-7dcf462d1ec1">

So, what i should suppose here? Can i use https://github.com/returntocorp/semgrep-rules/blob/release/yaml/semgrep/consistency/lang-consistency-bash.yaml for commercial purpose?

**Comment by LewisArdern** [comment]
@InternGoUser 

All semgrep-rules use the license as specified here https://github.com/returntocorp/semgrep-rules/blob/develop/LICENSE. which is Common Clause License.

As it states semgrep-rules cannot be resold without Semgrep, Inc. (“Semgrep”)’s permission", please read these two documents:
* https://semgrep.dev/docs/licensing/ 
* https://semgrep.dev/docs/faq/#how-are-semgrep-and-its-rules-licensed

Which mentions:

You cannot ship the Semgrep Community rules in a commercial product without an explicit license from Semgrep, Inc. For more information, please contact [partners@semgrep.com](mailto:partners@semgrep.com).
