### ISSUE TITLE
harden-dompurify-usage deprecation

### ISSUE THREAD

**Issue by aarongoldenthal** [returntocorp/sgrep-rules#3073]
**Describe the bug**

In https://github.com/returntocorp/semgrep-rules/commit/cee4603701e0eae34604fb4c628163310baac7ec, the `message` for rule `harden-dompurify-usage` was changed to "This rule has been deprecated.", but the `deprecated` key was not added to the `metadata`, per convention. This is necessary for system to properly filter out deprecated rules.

**Expected behavior**

The rule should be deprecated per convention:

```yaml
rules:
- id: harden-dompurify-usage
  metadata:
    deprecated: true
```

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Desktop (please complete the following information):**
 - OS: Windows 11, Ubuntu Linux

**Comment by LewisArdern** [comment]
We plan to delete all rules which have been deprecated in the near future, is this a mandatory requirement for your workflow? 

It's currently not a convention for Semgrep

**Comment by aarongoldenthal** [comment]
It's not required, but would be helpful. I filter the ruleset down to a subset, including removing deprecated rules, so having a specific key makes that easier. Using text like "has been deprecated" in the description to denote rule deprecation can be a problem because at least one rule has that text checking for a deprecated keyword (`dockerfile/best-practice/maintainer-is-deprecated.yaml`).

I originally thought it was a convention, but looking at all rules that does not appear to be the case (some have `deprecated: true`, some have "rule has been deprecated" or "rule is deprecated" in the description, and some have both).

Is there a specific convention for deprecated rules?

**Comment by LewisArdern** [comment]
As mentioned, we are going to be deleting all of our rules which have been deprecated so the convention will be they wont exist and you won't have to filter on rules anymore.

Does that solve the issue if we do that?

**Comment by aarongoldenthal** [comment]
That's perfect.
