### ISSUE TITLE
Issues with Rust Inside pattern matching from  1.27.0 to 1.41.0

### ISSUE THREAD

**Issue by Matthewbialek** [returntocorp/sgrep-rules#3128]
**Describe the bug**
We were previously on 1.27.0 due to the issues with semgrep being unable to run semgrep --test, now that this bug is fixed we tried to upgrade to 1.41.0. These two rules previously parsed.

**To Reproduce**
1. create a rule file :
rules:
  - id: sqlx-sqli
    languages:
      - rust
    message: >
      Detected string concatenation with a non-literal variable in a go-pg

      SQL statement. This could lead to SQL injection if the variable is user-controlled

      and not properly sanitized. In order to prevent SQL injection,

      used parameterized queries instead of string concatenation. You can use parameterized queries like so:

      '(SELECT ? FROM table, data1)'
    metadata:
      owasp: 'A1: Injection'
      references:
        - https://pg.uptrace.dev/
    severity: WARNING
    patterns:
      - pattern-either:
          - patterns:
              - pattern: |
                  sqlx::query!($QUERY)
              - pattern-either:
                  - pattern-inside: |
                      $QUERY = $X + $Y
                      ...
                  - pattern-inside: |
                      $QUERY += $X
                      ...
                  - pattern-inside: |
                      $QUERY = format!($PARAM1, ...)
                      ...
              - pattern-not-inside: |
                  $QUERY += "..."
                  ...
              - pattern-not-inside: |
                  $QUERY = "..." + "..."
                  ...
          - pattern: sqlx::query!($X + $Y)
          - pattern: sqlx::query!(format!("...", $PARAM1, ...))

2. Try to run tests.
3. Output
        rules/lang/security/injection/sqlx_sqli.yaml: Pattern parse error in rule sqlx-sqli:
 Invalid pattern for Rust:
--- pattern ---
$QUERY = format!($PARAM1, ...)
...

--- end pattern ---
Pattern error: Failure: no pattern found

**Expected behavior**
I expect the rule to parse like it did previously.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ X] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS

**Smartphone (please complete the following information):**

**Comment by p4p3r** [comment]
Hello @Matthewbialek, parsing for Rust has been greatly improved in the past few months, which also means it's more accurate "sensitive" to the code he accepts in the patterns :-)
In your case, the problem is that your `pattern-inside` and `pattern-not-inside` tries to match multiple statements, which in Rust have to be terminated by a semi-colon. Add all the required semi-colons and your parsing error will go away.
For example:
```rust
- pattern-inside: |
    $QUERY = format!($PARAM1, ...)
    ...
```
should be:
```rust
- pattern-inside: |
    $QUERY = format!($PARAM1, ...);
    ...
```
