### ISSUE TITLE
Add mapping to CWE-353

### ISSUE THREAD

**Issue by jmeit-fwdsec** [returntocorp/sgrep-rules#3134]
To make the rule **third-party-action-not-pinned-to-commit-sha** (linked below) work nicely with [ASVS](https://github.com/OWASP/ASVS) verifications, it would be helpful to add [CWE-353](https://cwe.mitre.org/data/definitions/353.html)_: Missing Support for Integrity Check_ to the list of CWEs for this rule. The existing CWE-1357 is also accurate, and since the "cwe" field in the rule can hold mutliple values, it would be useful to my team to add the one that maps nicely with ASVS.

Thank you.

https://github.com/returntocorp/semgrep-rules/blob/09efafd37cb8cee7b73fb1e1a1015550547178f4/yaml/github-actions/security/third-party-action-not-pinned-to-commit-sha.yml#L30

**Comment by p4p3r** [comment]
Hello @jmeit-fwdsec. It makes sense to me. It's going to be addresses by https://github.com/returntocorp/semgrep-rules/pull/3138

**Comment by jmeit-fwdsec** [comment]
Many thanks!
