### ISSUE TITLE
Remediation wrong for rule python.aws-lambda.security.dangerous-subprocess-use.dangerous-sub 

### ISSUE THREAD

**Issue by svbfromnl** [returntocorp/sgrep-rules#3162]
**Describe the bug**
The remedy for the test described in this rule link (https://sg.run/XZ7B) is not accurate. Python shlex does not have an escape() method, even back in Python2. Please update the rule and provide a new remediation tactic for tainted event objects.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Additional Context**
Currently ignoring this rule for my code.

**Comment by 0xDC0DE** [comment]
Thanks for reporting! I'll have a look!
