### ISSUE TITLE
Duplicate rules for Slack webhook URL

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-rules#3345]
There are two rules that warn about the same thing:

- [generic.secrets.gitleaks.slack-webhook-url](https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/gitleaks/slack-webhook-url.yaml)
- [generic.secrets.security.detected-slack-webhook](https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/security/detected-slack-webhook.yaml)

**Comment by Sjord** [comment]
Also for JWTs:

- [generic.secrets.security.detected-jwt-token](https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/security/detected-jwt-token.yaml)
- [generic.secrets.gitleaks.jwt](https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/gitleaks/jwt.yaml)

**Comment by LewisArdern** [comment]
A lot of people were asking for gitleaks, its an automated process and it gets updated if gitleaks changes their regex

Most people use Semgrep CI and gitleaks is not included in the default experience which means duplicate findings wouldn't occur for them.

For now we won't deduplicate, but will consider it in the future and can understand it may cause some frustration on those using direct clones of semgrep-rules
