### ISSUE TITLE
NextJS node modules vulnerabilities

### ISSUE THREAD

**Issue by Creakyinertia** [returntocorp/sgrep-rules#3445]
I’m using Next.js for my frontend. After building the project, I found some security vulnerabilities in semgrep report. Using the paths provided by Semgrep, I used a bundle analyzer to trace the chunks back to node modules. Some package files in node modules are flagged with security issues in Semgrep.

Q1: Is it recommended to exclude the node_modules directory from semgrep configurations?
Q2: Could the issues reported be false positives?
Q3: If there are no security vulnerabilities in your own codebase, is it necessary to analyze node_modules, which is beyond your control, using semgrep?

I would appreciate any insights based on your experience with these issues.

Thank you

**Comment by 0xDC0DE** [comment]
If you want to exclude the node_modules directory you can use a `.semgrepignore` file.
You can find more information in the Semgrep documentation.
https://semgrep.dev/docs/ignoring-files-folders-code 

Reporting false positives is only necessary if Semgrep flags patterns in the code that are clearly not vulnerable. In this case the findings are not in your code, but my assumption is that the pattern in the code itself is a valid finding, so no adjustment to the rule is necessary.
