### ISSUE TITLE
java.servlets.security.httpservlet-path-traversal.httpservlet-path-traversal shows false positive due to ignoring regex check

### ISSUE THREAD

**Issue by GiantCrocodile** [returntocorp/sgrep-rules#3502]
**Describe the bug**
This snippet of Java code is shown as vulnerable for rule `java.servlets.security.httpservlet-path-traversal.httpservlet-path-traversal`:

```java
[...]
		String filename = request.getParameter("img");
		String path = System.getProperty("<removed>") + "/<some>/<path>/";
		if (filename != null && !filename.isEmpty() && filename.matches("^[a-zA-Z0-9].[a-zA-Z0-9.]*$")
				&& new File(path + filename).exists()) {
			FileInputStream fileInput = new FileInputStream(path + filename);
[...]
```

At first I thought it's because it's possible somehow to use a `/` somewhere with two `.` but according to a quick test with https://regex101.com/ it seems to be not matching. Furthermore `path` is used as a prefix. I think there is an issue in the regex (not working exactly as expected) but there is no security issue involved so this finding is likely a false positive.

**Expected behavior**
Maybe some rule that warns me about a bug in the regex that isn't doing what it should likely (proper filename + file extension validation) but no security warning.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [x] P2: annoying but not blocking me

**Additional Context**
legacy code from a javax.servlet.http.HttpServlet application

Likely affects `httpservlet-path-traversal-deepsemgrep` and `spring-tainted-path-traversal` as well.

**Comment by 0xDC0DE** [comment]
Thanks for reporting this issue. It looks like the rule you mentioned does not have the `matches()` function as a sanitizer.  It's a very reasonable solution to this security problem, so I agree that the rule should be updated. 

The rules you mention are not open source rules, so I will move this ticket to an internal ticket.

**Comment by GiantCrocodile** [comment]
@0xDC0DE Is there an estimation when this could be fixed? Any update on the ticket? Thank you and have a great xmas time!

**Comment by GiantCrocodile** [comment]
@0xDC0DE Do you have by chance an update for the internal ticket on this? Thank you.
