### ISSUE TITLE
open-never-closed matching on implicit close

### ISSUE THREAD

**Issue by andyrat33** [returntocorp/sgrep-rules#552]
https://semgrep.live/scan/9998d52e-32cb-4516-be6c-ec247f54d23b

The rule identifies open without close but missed the use of 'with' and the implicit close

```py
    try:
        cc_file = open(filename, mode='rb')
    except IOError as e:
        print("Error: {}".format(e))
    else:
        with cc_file:
            for line in cc_file:
                for match in cc_pattern1.findall(line):
                    results.append( (match,filename,linePos) )
                linePos+=1
```

**Comment by minusworld** [comment]
We can filter out the simple case for this rule where everything happens in the same code block, but it looks like Semgrep has trouble with all the branches.

See this https://semgrep.live/j2QZ for an example. Semgrep should match in both cases.

**Comment by colleend** [comment]
Have we filed the `with` branch matching error?
