### ISSUE TITLE
PyYAML.load firing on ruaml.load

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#555]
ruaml.load is safe. Flagged in SaaS run on semgrep-app codebase

**Comment by minusworld** [comment]
This should work: https://semgrep.live/0oov

This is a weird corner case because import resolution in Python can't distinguish from `import yaml` and `yaml = ruamel.yaml.YAML(...)`. Fix for now is to filter out `yaml.load(...)` with `pattern-not-inside: yaml = $X; ...`
