### ISSUE TITLE
Ignore cases where constant strings are provided to django queryset `extra`

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep-rules#575]
Example failing test cases: https://semgrep.live/gxJK

Observed while scanning https://github.com/DefectDojo/django-DefectDojo/blob/de98f281165dedffb27a0a394fb0bbb66ed0e72e/dojo/metrics/views.py#L57-L69

Having dataflow here would help a lot.

**Comment by minusworld** [comment]
Others are beginning to request this as well.

The problem with filtering out constant strings is that they are still dangerous under specific circumstances:

https://docs.djangoproject.com/en/3.0/ref/models/querysets/#extra

The relevant bit reads:

> Warning
> 
> You should be very careful whenever you use extra(). Every time you use it, you should escape any parameters that the user can control by using params in order to protect against SQL injection attacks.
> 
> You also must not quote placeholders in the SQL string. This example is vulnerable to SQL injection because of the quotes around %s:
> 
> `SELECT col FROM sometable WHERE othercol = '%s'  # unsafe!`

The ideal solution for this rule, then, is to use `pattern-where-python` to script the conditions where this rule should fire.

I think, then, `python.django.security.audit.query-set-extra` should remain its own **audit** rule, and another rule should be made that flags dangerous use.

There is also `python.django.security.injection.sql.sql-injection-extra.sql-injection-using-extra-where`, part of the Django injection pack, which detects data from `request` going into `.extra(...)`. This is a much more accurate rule, at the cost of performance.

I think a new rule should be made that exists somewhere between the two that flags dangerous conditions: 1) string with placeholder OR 2) not a constant string.
