### ISSUE TITLE
Add trivial autofixes to checks that support them.

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#596]
- [x] Identify fixes for which trivial autofixes will work.
- [x] Create a test suite of actual vs. expected for each.
- [x] Add this to CI.
- [x] Add in ability to do regex replace in semgrep autofixes >.>
- [x] Make PR for these; when accepted, close issue.
- [ ] Highlight some of them on the semgrep.live examples dropdown

**Comment by minusworld** [comment]
Potential list of "trivial" autofixes for Java and Python:
https://returntocorp.quip.com/gZOMA2I4agyJ/v0-Autofix-Rules#BAIACAwhQTM

**Comment by minusworld** [comment]
See https://github.com/returntocorp/semgrep/pull/1025 for "trivial" autofixes for:

- `python.lang.security.unquoted-csv-writer.unquoted-csv-writer`
- `java.lang.security.audit.crypto.ssl.defaulthttpclient-is-deprecated.defaulthttpclient-is-deprecated`
- `python.django.security.passwords.use-none-for-password-default.use-none-for-password-default`
- `python.flask.best-practice.use-jsonify.use-jsonify`
- `python.requests.best-practice.use-timeout.use-timeout`

**Comment by aryx** [comment]
I think I have some ideas to improve the autofix on the ocaml-side. You would be able
to write a complex expression pattern using metavariables mentioned in the pattern and it would pretty print the correct code (right now I think there's a hack for it and many punctuations symbols are missing in the output). Let me know if this helps or if you have bugs with current autofix that my idea could help.

**Comment by minusworld** [comment]
This absolutely helps! Being able to use Semgrep for autofix in the same way we use it for matching is the best-case scenario.

@aryx If I collected some of the rules with autofixes and their examples, where would be the best place to give them to you?

**Comment by minusworld** [comment]
Before I can finish this, either need to update to newest Semgrep with `fix-regex` key included, or implement versioning.

Existing autofix rules are in develop branch of Semgrep here: https://github.com/returntocorp/semgrep/tree/develop/semgrep/tests/e2e/rules/autofix
