### ISSUE TITLE
semgrep.live bug report: java.lang.correctness.hardcoded

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep-rules#659]
This rule seems to have a lot of false positives on open-source corpi, see for example: https://semgrep.live/Ew4A

**Comment by mschwager** [comment]
Similar? https://github.com/returntocorp/semgrep-rules/issues/616

**Comment by ievans** [comment]
Yeah I think those are duplicate issues.

The root problem seems to be that we shouldn't be using the deep expression operator. Instead our pattern should probably be `if (false) { ... }` and let equivalences figure out that that's the same as `if (x && !x)`
