### ISSUE TITLE
Add equivalent eslint-plugin-security rules

### ISSUE THREAD

**Issue by mschwager** [returntocorp/sgrep-rules#683]
_Don't complete this - reserving for new hire task._

We've recently begun porting common static analysis/linter tool rules over to `semgrep`. This makes for an easy transition if a user/customer is already using this tool. For example, we've already ported the following tools:

* Golang's [`gosec`](https://github.com/securego/gosec) - https://semgrep.live/p/gosec
* Java's [`find-sec-bugs`](https://github.com/find-sec-bugs/find-sec-bugs) - https://semgrep.live/p/findsecbugs
* Python's [`bandit`](https://github.com/openstack-archive/bandit) - https://semgrep.live/p/bandit

Similarly, let's create an equivalent checkpack for [`eslint-plugin-security`](https://github.com/nodesecurity/eslint-plugin-security). The goal of this task is to port over rules from `eslint-plugin-security` to `semgrep`. This can be accomplished by creating the appropriate rules in Javascript security directory: https://github.com/returntocorp/semgrep-rules/tree/develop/javascript/lang/security, similar to `find-sec-bugs` in the Java security directory: https://github.com/returntocorp/semgrep-rules/tree/develop/java/lang/security.

Briefly looking through the rules, we probably don't need all of them. We want to balance coverage vs. potential for false positives. I.e. people don't like incorrect, noisy rules. Looking through the list I would say we can avoid the following because they may be too noisy:

* detect-unsafe-regex
* detect-non-literal-fs-filename
* detect-non-literal-regexp
* detect-possible-timing-attacks

**Comment by clintgibler** [comment]
I haven't reviewed these in detail, but we could also consider the following from Mozilla:
* https://github.com/mozilla/eslint-plugin-amo
* https://github.com/mozilla/eslint-plugin-no-unsanitized

**Comment by minusworld** [comment]
- [ ] [`detect-unsafe-regex`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-unsafe-regex.js) - uses the [safe-regex](https://www.npmjs.com/package/safe-regex) to validate that a regex is not potentially open to catastrophic exponential-time increases.
- [ ] <strike>[`detect-buffer-noassert`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-buffer-noassert.js) - detects use of `noAssert` in `Buffer` APIs, which bypasses validation of `offset`. This is [deprecated as of Node v10.0.0](https://nodejs.org/api/all.html#deprecations_dep0102_using_noassert_in_buffer_read_write_operations). Won't port.</strike>
- [ ] [`detect-child-process`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-child-process.js) - detects `require('child_process')` and non-literal calls to `child_process.exec()`
- [ ] [`detect-disable-mustache-escape`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-disable-mustache-escape.js) - detects `$OBJ.escapeMarkup = false` which disables escaping in the mustache template engine.
- [ ] [`detect-eval-with-expression`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-eval-with-expression.js) - detects `eval()` with non-literal argument
- [ ] [`detect-no-csrf-before-method-override`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-no-csrf-before-method-override.js) - Express.js rule for detecting CSRF being set up before method override which could let `GET` become `POST` later.
- [ ] [`detect-non-literal-fs-filename`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-non-literal-fs-filename.js) - detects non-literal filenames in `fs` calls
- [ ] [`detect-non-literal-regexp`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-non-literal-regexp.js) - detects non-literals in `RegExp`. Goal is to avoid user injection causing ReDoS
- [ ] [`detect-object-injection`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-non-literal-regexp.js) - detects use of square-bracket notation on objects where the key value is a variable, which could allow arbitrary assignments on accesses on the object.
- [ ] [`detect-possible-timing-attacks`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-possible-timing-attacks.js) - detects naive comparisons of sensitive values such as password hashes which does character-by-character comparisons. This results in a timing attack which can reduce brute-force complexity.
- [ ] [`detect-pseudoRandomBytes`](https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-pseudoRandomBytes.js) - detect `psuedoRandomBytes()` which does not produce secure random numbers

**Comment by mschwager** [comment]
> ~detect-buffer-noassert - detects use of noAssert in Buffer APIs, which bypasses validation of offset. This is deprecated as of Node v10.0.0. Won't port.~

Do we have a good reason not to port this? Catching this in legacy code may still be a useful check.
