### ISSUE TITLE
C: example goto fail test is inverted

### ISSUE THREAD

**Issue by philpennock** [returntocorp/sgrep-rules#704]
**Describe the bug**

The example C rule inverts what it's looking for and only triggers on correct code, while staying silent on the vulnerability it is supposed to detect.

```yaml
- id: double_goto
  pattern: |
    if ($COND) {
      goto $FAIL;
      goto $FAIL;
    }
  message: The second goto statement will always be executed
```

The braces mean that the second $FAIL will not always be executed.  The vulnerability is that when the braces are missing, it will be.

**To Reproduce**

```c
#include <stdio.h>

int
main(int argc, char *argv[]) {
	if (0)
		goto ONE;
		goto ONE;
	printf("did not go to one\n");
	return 0;
ONE:
	printf("went to one\n");
	return 1;
}
```

Run semgrep against this and it will stay silent.  Compile it and run and you'll see the bug.  Add braces for the conditional and run semgrep and it will falsely complain, compile and run and you'll see it exits 0.

**Expected behavior**

An example rule for C which has been tested is always a nice plus for learning an intriguing new tool.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

Rule from semgrep-rules commit 943d58e

**Comment by minusworld** [comment]
Hi @philpennock ! Thanks for the issue. If I'm reading this correctly, the braces need to be removed from the Semgrep rule in order to correctly identify the issue. Is that right?

Here's the rule modified without braces: https://semgrep.live/JD0w/

Thanks again!

**Comment by philpennock** [comment]
LGTM

**Comment by minusworld** [comment]
Awesome! I'll update the rule.
