### ISSUE TITLE
[Check] Secret scanning

### ISSUE THREAD

**Issue by clintgibler** [returntocorp/sgrep-rules#731]
**Check Description**

- [ ] This ticket has links, references, or examples.
- [ ] Your check has true positive and true negative test cases.
- [ ] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket. If there are no findings, paste the triager link anyway.
- [ ] Your check PR has been reviewed and merged.
Now, close the ticket!

Secrets detection tools we should review:
* [ ] TruffleHog v3 - https://github.com/trufflesecurity/TruffleHog
* [ ] https://github.com/dxa4481/truffleHog
  * https://github.com/dxa4481/truffleHog/blob/48ffdd3beee3b600939136fccad59f50a2610909/scripts/searchOrg.py#L10
* [ ] https://github.com/Yelp/detect-secrets
  * https://github.com/Yelp/detect-secrets/tree/master/detect_secrets/plugins
* [ ] https://github.com/thoughtworks/talisman
* [ ] https://github.com/Plazmaz/leaky-repo
* [ ] https://github.com/Skyscanner/whispers
* [ ] https://github.com/owasp/sedated
* [ ] https://github.com/michenriksen/gitrob/blob/master/core/signatures.go
* [ ] https://github.com/nielsing/yar
* [ ] [Token-Hunter](https://gitlab.com/gitlab-com/gl-security/security-operations/gl-redteam/token-hunter) - [blog post](https://about.gitlab.com/blog/2019/12/20/introducing-token-hunter/)
* [ ] [credential-digger](https://github.com/SAP/credential-digger)
* [ ] [gitlab-watchman](https://github.com/PaperMtn/gitlab-watchman)
* [ ] [gitleaks](https://github.com/zricethezav/gitleaks)
* [ ] https://semgrep.dev/p/hazanasec.possible_hardcoded_secrets
* [ ] [gitdorker](https://www.kitploit.com/2020/10/gitdorker-tool-to-scrape-secrets-from.html)
* [ ] https://github.com/internetwache/GitTools
* [ ] https://github.com/hisxo/gitGraber
* [ ] https://github.com/dwisiswant0/gf-secrets
* [ ] https://github.com/newrelic/rusty-hog
* [ ] https://github.com/datumbrain/aws-macie-pii-confidential-regexes/blob/master/regex_list.csv
* [ ] https://github.com/SnaffCon/Snaffler
* [ ] https://github.com/grab/secret-scanner
* [ ] https://github.com/eth0izzle/shhgit/
* [ ] https://github.com/jtmelton/camas
* [ ] https://github.com/deepfence/SecretScanner - note: uses the same `config.yaml` checks as shhgit
    * [ ] Used by [ThreatMapper](https://github.com/deepfence/ThreatMapper)
* [ ] https://github.com/owenrumney/squealer
* [ ] https://github.com/gocaio/gap
* [ ] https://github.com/dwisiswant0/apkleaks
* [ ] https://cloudsecdocs.com/devops/tooling/secrets/
* [ ] https://github.com/0xTeles/jsleak | https://github.com/KathanP19/JSFScan.sh
* [ ] https://github.com/stacscan/stacs
* [ ] https://github.com/databricks/security-bucket-brigade/blob/master/Tools/s3-secrets-scanner/rules.json
* [ ] https://github.com/sirwart/ripsecrets
* ...

More from this thread: https://twitter.com/Jhaddix/status/1323396377997553664

[Introducing PinataHub: Explore the world of leaked secrets in GitHub](https://incognitatech.medium.com/introducing-pinatahub-explore-the-world-of-leaked-secrets-in-github-522aa5060a51)

> If you have used any open-source tools for secret detection (many exist), or even a pricey SaaS solution, you will probably have figured out that they work well only when the secrets are leaked in obvious and expected ways (e.g. have a clear declaration, high complexity, etc.), or when they are issued by a service that provides credentials in a identifiable and distinguishable format (e.g. AIza[0–9A-Za-z-_]{35}). But in reality, source code can be arbitrarily complex. GoldDigger outperforms every existing secret detection solution, leveraging an intelligent context analysis scheme which uses an extensive set of novel lexical and statistical features to tackle the challenge of capturing credential leaks in the wild. These features were inspired by our research in the field of Algorithmically Generated Domain (AGD) detection. Although the problem of detecting secrets in source code and detecting malicious AGDs employed by threat actors might appear totally different, they have much common ground: In both cases, the effectiveness of a detector is determined by its capability to capture patternless outliers in relatively short strings.

> In terms of detecting leaked secrets in source code, we based our solution on the following two assumptions:
> 1. The majority of public Github repositories do not include any leaked secrets (hopefully).
> 2. Meaningful credentials are relatively unique compared to other tokens.

> To this end, we were able to create a baseline model of tokens that commonly occur close to credential-related keywords, and use it to identify sensitive strings that are highly likely to be secrets. This way, the secret detection scheme implemented in GoldDigger is capable of pinpointing actual secrets with great accuracy, vastly reducing the amount of false positives commonly returned by regex or entropy based approaches.

[nightwatchcybersecurity/gitbleed_tools](https://github.com/nightwatchcybersecurity/gitbleed_tools)
Tool by [Nightwatch Cybersecurity](https://twitter.com/nightwatchcyber) for
calculating the delta between a regular cloned repo and a mirrored (`--mirror`)
one, and scanning the parts only available in the mirror for secrets using
gitleaks. [Blog post](https://wwws.nightwatchcybersecurity.com/2022/02/11/gitbleed/) with more info, including how `--mirror` mode can include additional repo content that isn't present in normal clones.

**Comment by dlukeomalley** [comment]
@clintgibler I've gotten a few more secret scanning asks. Thoughts on where this falls on the roadmap?

CC @daghan
