### ISSUE TITLE
Refactor rules with poor performance

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#736]
**Describe the bug**
These rules run at under 1,000 lines of code per second based on [this benchmark](https://github.com/minusworld/semgrep-rules/actions/runs/175034968)

```
javascript/express/security/express-jwt-hardcoded-secret.yaml
contrib/nodejsscan/nosql_injection.yaml
javascript/express/security/audit/res-render-injection.yaml
contrib/nodejsscan/archive_path_overwrite.yaml
python/lang/maintainability/useless-innerfunction.yaml
javascript/passport-jwt/security/passport-hardcode.yaml
javascript/express/security/require-request.yaml
contrib/nodejsscan/hardcoded_secrets.yaml
contrib/nodejsscan/xss_node.yaml
javascript/express/security/audit/express-xml2json-xxe-event.yaml
contrib/nodejsscan/header_cors_star.yaml
javascript/express/security/express-sandbox-injection.yaml
javascript/express/security/express-xml2json-xxe.yaml
javascript/jsonwebtoken/security/audit/jwt-exposed-data.yaml
python/django/security/injection/email/xss-send-mail-html-message.yaml
javascript/jsonwebtoken/security/audit/jwt-decode-without-verify.yaml
javascript/jose/security/audit/jose-exposed-data.yaml
javascript/vm2/security/audit/vm2-context-injection.yaml
python/django/best-practice/json_response.yaml
python/django/security/injection/command/command-injection-os-system.yaml
javascript/express/security/express-puppeteer-injection.yaml
javascript/express/security/audit/express-jwt-not-revoked.yaml
javascript/express/security/express-phantom-injection.yaml
javascript/express/security/express-expat-xxe.yaml
python/django/security/injection/sql/sql-injection-using-raw.yaml
python/django/security/injection/sql/sql-injection-rawsql.yaml
python/django/security/injection/sql/sql-injection-using-db-cursor-execute.yaml
contrib/dlint/dlint-equivalent.yaml
javascript/express/security/express-wkhtml-injection.yaml
javascript/express/security/express-vm2-injection.yaml
python/django/security/injection/sql/sql-injection-extra.yaml
javascript/lang/security/audit/vm-injection.yaml
javascript/express/security/express-vm-injection.yaml
javascript/express/security/audit/express-path-join-resolve-traversal.yaml
javascript/lang/security/audit/path-traversal/path-join-resolve-traversal.yaml
javascript/express/security/audit/express-cookie-settings.yaml
javascript/wkhtmltoimage/security/audit/wkhtmltoimage-injection.yaml
javascript/phantom/security/audit/phantom-injection.yaml
javascript/wkhtmltopdf/security/audit/wkhtmltopdf-injection.yaml
javascript/sandbox/security/audit/sandbox-code-injection.yaml
javascript/vm2/security/audit/vm2-code-injection.yaml
python/django/security/injection/path-traversal/path-traversal-join.yaml
python/django/security/injection/path-traversal/path-traversal-file-name.yaml
javascript/puppeteer/security/audit/puppeteer-injection.yaml
```

**Goal**
Let's refactor these rules to make sure they run faster than 1,000 sloc/sec.

**Ideas**
- Split large rules into smaller rules per file.
- Use `pattern-regex` instead of `pattern-inside` for import or package detection.
- Try out the new tainting engine.

** More Info: **
Benchmark job: https://github.com/returntocorp/semgrep-rules/actions?query=workflow%3Arule-benchmarks. This runs every weekend. The job uploads a few artifacts which can be downloaded. If you download the test logs, there are two relevant pieces of information in there. One is the benchmark table, which roughly shows the performance of every rule that completes in under 60 seconds. Then, any failed tests are rules that did not complete within 60 seconds. Those are the rules that populated the list above.

To improve performance, let's see if we can split larger rules into smaller rules.
- If there is more than one rule in a file, split each rule into its own file.
- If we can logically separate rules into smaller chunks and still get the same coverage, let's do that too!
- Recommend starting with `python/django/security/injection` rules since we have the most context on those.
- Ignore `contrib` rules for now until we integrate them as submodules.

**Comment by ajinabraham** [comment]
Just a quick note. https://github.com/semgrep/rules-nodejsscan is more updated than `contrib/nodejsscan`

**Comment by minusworld** [comment]
I suppose we could make this a submodule here.
