### ISSUE TITLE
CI is busted due to Docker change

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep-rules#773]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2374948/89819707-b7e5e000-db00-11ea-82f6-a485048c72dd.png)

**To Reproduce**
https://github.com/returntocorp/semgrep-rules/actions/runs/202874539

**Comment by nbrahms** [comment]
Fixed in https://github.com/returntocorp/semgrep-rules-test-action-develop/commit/e78597e4667a8470aad554c0e21494e4fd3fe1f5
