### ISSUE TITLE
Crypto Rule Pack

### ISSUE THREAD

**Issue by colleend** [returntocorp/sgrep-rules#774]
**Check Pack Description**

Detect uses of bad entropy, specific RSA keys, RSA keys that are too short, weak elliptic curves, etc.

**Comment by dgryski** [comment]
Comparing MACs with == instead of a constant time operation.

Here's my Go scanner that does this: https://github.com/dgryski/semgrep-go/blob/master/hmac-bytes.yml

**Comment by clintgibler** [comment]
Nice, thanks @dgryski 👍 

Also, FYI @hazanasec has a few crypto rules he's been fleshing out for the ASVS repo: https://github.com/hazanasec/rules-owasp-asvs/blob/master/v6/java/6.2.5.yaml

**Comment by tsluyter** [comment]
Great idea! I was just thinking that it should be do-able to check for bad situations, where people skipped setting an IV or where keys are generated based on hard-coded secrets.

**Comment by colleend** [comment]
yes definitely! these are great ideas. we have a few crypto rules that exist currently, but it would be nice to have more thorough coverage 😁
