### ISSUE TITLE
don't use .extra()

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#80]
avoid, use .raw() instead

**Comment by ulziibay** [comment]
Seems like inheritance support (during import resolution) is necessary for this. That is not implemented at the moment!
snippet
```python
class Entry(models.Model):
   ....
Entry.objects.get()
```

```
django.db.models.Model.objects.get()
```

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/filter/627?check_ids=sgrep-rules.python.django.db.query.avoid-query-set-extra

**Comment by minusworld** [comment]
Improve the check using advice in the "Warning" section. Can improve with dataflow.

https://docs.djangoproject.com/en/3.0/ref/models/querysets/#django.db.models.query.QuerySet.extra
