### ISSUE TITLE
False positive in HTTP Delete method

### ISSUE THREAD

**Issue by javixeneize** [returntocorp/sgrep-rules#819]
Hi

Semgrep has detected a sql injection in a http call that uses a DELETE method. It is a clear false positive, as there is no sql interaction on all. I think it believes that, as the sentence contains DELETE and concatenation (+), it believes it is a sql injection

```java
 latestResponse = restTemplate
                .execute(baseUrl + url, HttpMethod.DELETE, requestCallback, response -> {
                    if (errorHandler.hadError) {
                        return (errorHandler.getResults());
                    } else {
                        return (new ResponseResults(response));
                    }
                });
```

The rule triggered is `java.lang.security.audit.formatted-sql-string.formatted-sql-string`, which is part of findsecuritybugs package.

Using findsecbugs itself (spotbugs), this false positive is not flagged, so it brings me another question... Are the rules in the findsecbugs the official ones, or have those been adapted by you to semgrep?

Thanks

**Comment by underyx** [comment]
Thanks for the report! I've created a snippet that shows the false positive so that we can debug this more easily: https://semgrep.dev/s/underyx:issue-819?stepByStep=1

@minusworld will you be able to have a look?

**Comment by javixeneize** [comment]
Great ;)

Can you also help to find out how those findsecbugs rules have been written?
Thanks

**Comment by underyx** [comment]
Oh, my bad, I missed that question. You're right that we've adapted these rules ourselves as part of our efforts to give people a couple familiar rulesets: we've ported `bandit` for Python, `gosec` for Golang, and `findsecbugs` for Java ourselves. Also, `nodejsscan` has been ported by its original author.

**Comment by javixeneize** [comment]
That’s a good effort ;) 

Probably findsecbugs team can help to review those rules and adapt those to semgrep. Philippe is aware of this problem as I initially reported it to him

**Comment by underyx** [comment]
Sounds good, thank you!

**Comment by inkz** [comment]
I thought we improved this rule :thinking: we created better SQLi rules since then, but his one definitely need to be updated

**Comment by XhstormR** [comment]
ping

**Comment by inkz** [comment]
@XhstormR the rule is improved https://github.com/returntocorp/semgrep-rules/blob/develop/java/lang/security/audit/formatted-sql-string.yaml and the false positive issue mentioned above is mitigated.
