### ISSUE TITLE
avoid csrf_exempt decorator

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#82]
only very occasionally is this ok

**Comment by minusworld** [comment]
https://docs.djangoproject.com/en/3.0/ref/csrf/#scenarios

**Comment by minusworld** [comment]
Triaged: https://dev.massive.ret2.co/triager/score/613?check_id=tmp.django-csrf_exempt

**Comment by minusworld** [comment]
Score could be improved easily by looking for state-changing operations within the function.
e.g., Model.save(), writing files to disk, etc.
