### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by matthieucan** [returntocorp/sgrep-rules#899]
**Is your feature request related to a problem? Please describe.**
As far as I know, the content of this repository is not licensed, meaning nothing can be legally done (cloning, executing, making derived works, etc). It is a pity, semgrep is a brilliant tool and this collection of rules is very useful.

**Describe the solution you'd like**
Add a software or CC license.

**Describe alternatives you've considered**
I'm not aware of any alternative to licensing.

**Additional context**
Nothing to add, thanks for the great tool!

**Comment by dlukeomalley** [comment]
Thanks @matthieucan for the ticket. @DrewDennison, do you have any context you can add?

**Comment by DrewDennison** [comment]
hey @matthieucan thanks for the ticket and yes, our intention is to make all these rules open source for the community to use, remix, and contribute. The discussion we've had internally has been do we treat this as code and licence AGPL etc or as a database of rules data and make it [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) 

I'm leaning towards CC but I would love your feedback on what license you would be most excited about contributing under or if there are any "no go" licenses for you. I should be able to add a license this week. Do you need it on a sooner timeline?

**Comment by matthieucan** [comment]
Hey @dlukeomalley @DrewDennison, thanks for replying so fast and being open to community input!

I suppose you meant LGPL, and not AGPL? IANAL, but I believe you're right on point by questioning LGPL vs CC-BY-SA, i.e. is this repository an (embeddable) library, or a database/collection of (non-software) works?

This collection of rules is not really software, but it is still interpreted and understood by computers. So the freedom of execution granted by LGPL makes sense here.
On the other hand, this database of rules could be used in new creative ways, and leaving some legal buffer for this collection to not be used only as a "library", would surely benefit those creative users. In this regard CC-BY-SA makes sense. I don't have any example of the unforeseen things that could be built with it, but that's the whole point.

So, what do you think about dual-licensing? Best of both worlds?

**Comment by DrewDennison** [comment]
@matthieucan thanks for the thoughtful reply. I'm double checking with our lawyer this week and should have this merged shortly

**Comment by ievans** [comment]
@matthieucan this is resolved now by https://github.com/returntocorp/semgrep-rules/pull/968 -- I'll let you read the full context there, and feel free to comment on the PR even though it's merged if you have feedback!

**Comment by matthieucan** [comment]
@ievans Thank you for taking care of this so fast!

**Comment by pombredanne** [comment]
IMHO there is still a license problem. See:

- https://github.com/returntocorp/semgrep-rules/pull/968#issuecomment-926947042
