### ISSUE TITLE
use earliest(field)/latest(field) instead of order_by(field)[0] etc

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep-rules#92]

**Comment by nbrahms** [comment]
Per the Django documentation,

> Note that earliest() and latest() exist purely for convenience and readability.

This appears to be a style check, rather than a performance check?

**Comment by minusworld** [comment]
🤔 Good to note for later, definitely. We could group in django/style for now

**Comment by jacobian** [comment]
Yup, I'd agree with the documentation. It'd not about anything technical, but about communicating to a (human) reader what the code's intent is. `order_by(date_created)[-1]` isn't quite as clear as `latest('date_created')` (at least, to my eyes).

(Same's indeed true of `first/last`)

So yeah, calling it "style" or "readability" seems correct to me.

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/filter/627?check_ids=sgrep-rules.python.django.performance.use-earliest-or-latest
